const C=window.ONE_MUSLIM_CONFIG||{};
const supabaseClient=(C.SUPABASE_URL&&C.SUPABASE_ANON_KEY&&window.supabase)?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const demoKey='oneMuslimV3Demo';
const defaultAvatar={gender:'male',maleBase:'male-1',maskColor:'white',headwear:'none',shirtColor:'black',backgroundColor:'default',eyeGlowColor:'none'};
const demo={user:null,profiles:[
{id:'demo-1',name:'Amina Hassan',city:'Minneapolis',state:'MN',country:'United States',bio:'Learning, growing and connecting.',map:true,rankPoints:100,avatar:{...defaultAvatar,maleBase:'male-1'}},
{id:'demo-2',name:'Yusuf Ali',city:'Toronto',state:'ON',country:'Canada',bio:'Community builder.',map:true,rankPoints:100,avatar:{...defaultAvatar,maleBase:'male-2'}},
{id:'demo-3',name:'Layla Omar',city:'London',state:'',country:'United Kingdom',bio:'Always learning.',map:true,rankPoints:100,avatar:{...defaultAvatar,maleBase:'male-3'}}],
posts:[{id:'p1',name:'One Muslim',body:'Welcome to One Muslim — a place to connect, learn and grow together.',time:Date.now()-7200000},{id:'p2',name:'Community',body:'New revert? You are welcome here. Your journey starts with one step.',time:Date.now()-3600000}],session:null};
let state=JSON.parse(localStorage.getItem(demoKey)||'null')||demo;
const save=()=>localStorage.setItem(demoKey,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=t=>new Date(t).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const maleOptions=[['male-1','Complexion 1'],['male-2','Complexion 2'],['male-3','Complexion 3']];
const maskOptions=[['white','White'],['black','Black'],['teal','Teal'],['gold','Gold'],['royal-blue','Royal Blue'],['emerald','Emerald'],['crimson','Crimson'],['purple','Purple']];
const headwearOptions=[['none','None'],['hat','Hat'],['scarf','Islamic Scarf']];
const shirtOptions=[['black','Black'],['white','White'],['teal','Teal'],['gold','Gold'],['blue','Blue']];
const bgOptions=[['default','Default'],['mint','Mint'],['sky','Sky'],['sand','Sand'],['night','Night']];
const eyeOptions=[['none','None'],['teal','Teal'],['gold','Gold'],['blue','Blue'],['purple','Purple'],['red','Red']];
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2600)}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));const target=document.getElementById(page+'Page');if(!target)return;target.classList.remove('hidden');history.replaceState(null,'','#'+page);if(page==='map')renderMap();if(page==='community')renderCommunity();if(page==='events')renderEvents();if(page==='profile')renderProfile();renderHeader()}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.nav)));
function openAuth(signup=true){document.getElementById('authModal').classList.remove('hidden');setAuthMode(signup)}
function closeAuth(){document.getElementById('authModal').classList.add('hidden')}
function setAuthMode(signup){document.getElementById('authTitle').textContent=signup?'Join the community':'Welcome back';document.getElementById('authSub').textContent=signup?'Create your account and start building your profile.':'Sign in to continue your journey.';document.getElementById('authName').closest('label').style.display=signup?'grid':'none';document.getElementById('authSwitch').textContent=signup?'Already have an account? Sign in':'Need an account? Create one';document.getElementById('authForm').querySelector('.primary').textContent=signup?'Create account':'Sign in';document.getElementById('authForm').dataset.mode=signup?'signup':'login';document.getElementById('authStatus').textContent=''}
document.getElementById('closeAuth').onclick=closeAuth;document.getElementById('joinBtn').onclick=()=>openAuth(true);document.getElementById('heroJoin').onclick=()=>openAuth(true);document.getElementById('signInBtn').onclick=()=>openAuth(false);['mapJoin','eventJoin','communityJoin','journeyJoin'].forEach(id=>document.getElementById(id).onclick=()=>openAuth(true));document.getElementById('authSwitch').onclick=()=>setAuthMode(document.getElementById('authForm').dataset.mode!=='signup');
document.getElementById('googleBtn').onclick=async()=>{if(!supabaseClient){document.getElementById('authStatus').textContent='Google Auth is ready for Supabase. Add SUPABASE_URL and SUPABASE_ANON_KEY in config.js, then enable Google in Supabase Auth.';return}const {error}=await supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)document.getElementById('authStatus').textContent=error.message};
document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const mode=e.currentTarget.dataset.mode;if(supabaseClient){let r;if(mode==='signup')r=await supabaseClient.auth.signUp({email:authEmail.value,password:authPassword.value,options:{data:{display_name:authName.value.trim()}}});else r=await supabaseClient.auth.signInWithPassword({email:authEmail.value,password:authPassword.value});if(r.error){authStatus.textContent=r.error.message;return}closeAuth();await hydrateUser();toast(mode==='signup'?'Welcome to One Muslim!':'Welcome back!');go(mode==='signup'?'profile':'community');return}const email=authEmail.value.trim().toLowerCase();if(mode==='signup'){if(state.profiles.some(p=>p.email===email)){authStatus.textContent='An account with that email already exists.';return}const p={id:'local-'+Date.now(),name:authName.value.trim(),email,city:'',state:'',country:'',bio:'',map:false,rankPoints:100,rankAwards:{},avatar:{...defaultAvatar}};state.profiles.push(p);state.user=p;state.session=p.id;save();closeAuth();renderHeader();go('profile');toast('Account created — you start at Rank 100.')}else{const p=state.profiles.find(x=>x.email===email);if(!p){authStatus.textContent='Demo mode: create an account first.';return}state.user=p;state.session=p.id;save();closeAuth();renderHeader();go('community');toast('Signed in!')}};
async function hydrateUser(){if(!supabaseClient)return;const {data}=await supabaseClient.auth.getUser();if(!data.user)return;let p=state.profiles.find(x=>x.id===data.user.id);if(!p){p={id:data.user.id,name:data.user.user_metadata?.display_name||data.user.email?.split('@')[0]||'Member',email:data.user.email,city:'',state:'',country:'',bio:'',map:false,rankPoints:100,rankAwards:{},avatar:{...defaultAvatar}};state.profiles.push(p)}p.rankPoints=p.rankPoints||100;p.avatar={...defaultAvatar,...(p.avatar||{})};state.user=p;state.session=p.id;save();renderHeader()}
async function logout(){if(supabaseClient)await supabaseClient.auth.signOut();state.user=null;state.session=null;save();renderHeader();go('home');toast('Signed out.')}
function avatarSrc(av){av={...defaultAvatar,...(av||{})};if(av.maleBase==='male-1'||av.maleBase==='male-2'||av.maleBase==='male-3'){return `assets/avatar/male/${av.maleBase}-mask-${av.maskColor||'white'}.jpg`}return 'assets/avatar/male/male-1-mask-white.jpg'}
function renderHeader(){const u=state.user;document.getElementById('signInBtn').classList.toggle('hidden',!!u);document.getElementById('joinBtn').classList.toggle('hidden',!!u);const b=document.getElementById('profileBtn');b.classList.toggle('hidden',!u);if(u){document.getElementById('profileBtnName').textContent=u.name||'Member';document.getElementById('headerRank').textContent=u.rankPoints||100;document.getElementById('headerAvatar').src=avatarSrc(u.avatar);b.onclick=()=>go('profile')}}
function award(u,key,points){u.rankPoints=u.rankPoints||100;u.rankAwards=u.rankAwards||{};if(!u.rankAwards[key]){u.rankPoints+=points;u.rankAwards[key]=true;return points}return 0}
function renderAvatarControls(){const u=state.user;if(!u)return;u.avatar={...defaultAvatar,...(u.avatar||{})};const unlocked=(u.rankPoints||100)>=1000;const wrap=document.getElementById('avatarControls');
const group=(title,items,key,locked=false)=>`<div class="control-group"><b>${title}${locked?' <span class="lock">🔒 1,000 Rank</span>':''}</b><div>${items.map(([v,l])=>`<button type="button" class="choice ${u.avatar[key]===v?'active':''} ${locked?'locked':''}" data-g="${key}" data-v="${v}" ${locked?'disabled':''}>${l}</button>`).join('')}</div></div>`;
wrap.innerHTML=group('Male complexion',maleOptions,'maleBase')+`<div class="control-group"><b>Female</b><div><button type="button" class="choice locked" disabled>Coming soon</button></div></div>`+group('Mask color',maskOptions,'maskColor',!unlocked)+group('Headwear',headwearOptions,'headwear',!unlocked)+group('Shirt color',shirtOptions,'shirtColor',!unlocked)+group('Background',bgOptions,'backgroundColor',!unlocked)+group('Eye glow',eyeOptions,'eyeGlowColor',!unlocked);
wrap.querySelectorAll('.choice:not([disabled])').forEach(b=>b.onclick=()=>{u.avatar[b.dataset.g]=b.dataset.v;applyAvatar(u.avatar);renderAvatarControls()});applyAvatar(u.avatar);document.getElementById('rankValue').textContent=u.rankPoints||100;document.getElementById('unlockText').textContent=unlocked?'Customization unlocked 🎉':`${Math.max(0,1000-(u.rankPoints||100))} more points to unlock customization`}
function applyAvatar(av){av={...defaultAvatar,...av};const img=document.getElementById('avatarCharacter');img.src=avatarSrc(av);img.style.background=({default:'#f7fbff',mint:'#e5f7f2',sky:'#eaf3ff',sand:'#f6eedc',night:'#182334'}[av.backgroundColor]||'#f7fbff');img.style.borderRadius='22px';document.getElementById('headerAvatar')?.setAttribute('src',avatarSrc(av))}
function renderProfile(){const u=state.user;if(!u){document.getElementById('profileStatus').textContent='Sign in to edit your profile.';return}profileName.value=u.name||'';profileBio.value=u.bio||'';profileCity.value=u.city||'';profileState.value=u.state||'';profileCountry.value=u.country||'';profileMap.checked=!!u.map;renderAvatarControls();renderHeader()}
document.getElementById('profileForm').onsubmit=e=>{e.preventDefault();if(!state.user){openAuth(true);return}const u=state.user;const before=u.rankPoints||100;Object.assign(u,{name:profileName.value.trim(),bio:profileBio.value.trim(),city:profileCity.value.trim(),state:profileState.value.trim(),country:profileCountry.value.trim(),map:profileMap.checked});award(u,'name',10);if(u.bio)award(u,'bio',10);if(u.city&&u.country)award(u,'location',15);if(u.map)award(u,'map',10);const i=state.profiles.findIndex(p=>p.id===u.id);if(i>=0)state.profiles[i]=u;save();renderHeader();renderAvatarControls();profileStatus.textContent=u.rankPoints>before?`Saved. You earned ${u.rankPoints-before} Rank points.`:'Saved.';toast(u.rankPoints>before?`Profile saved — Rank ${u.rankPoints}.`:'Profile updated.')};
document.getElementById('saveAvatar').onclick=()=>{if(!state.user){openAuth(true);return}award(state.user,'avatar',25);save();renderHeader();renderAvatarControls();avatarStatus.textContent=`Avatar saved. Rank ${state.user.rankPoints}.`;toast(`Avatar saved — Rank ${state.user.rankPoints}.`)};
function renderHome(){homeFeed.innerHTML=state.posts.slice().sort((a,b)=>b.time-a.time).slice(0,3).map(p=>`<article class="feed-item"><b>${esc(p.name)}</b><small>${fmt(p.time)}</small><p>${esc(p.body)}</p></article>`).join('');homeEvents.innerHTML=events.slice(0,3).map(e=>`<div class="event-mini"><b>${e.title}</b><span>${e.date} · ${e.city}</span></div>`).join('')}
const events=[{title:'Community Welcome Night',date:'Sep 5',city:'Minneapolis',kind:'Community'},{title:"Qur'an Circle",date:'Sep 8',city:'Toronto',kind:'Learning'},{title:'New Muslim Meet & Greet',date:'Sep 12',city:'London',kind:'New Muslims'},{title:'Family Community Day',date:'Sep 20',city:'Minneapolis',kind:'Families'}];
function renderEvents(){eventsGrid.innerHTML=events.map(e=>`<article class="event-card-large"><span>${e.kind}</span><h3>${e.title}</h3><p>📅 ${e.date}<br>📍 ${e.city}</p><button class="secondary">View event</button></article>`).join('')}
function renderCommunity(){communityFeed.innerHTML=state.posts.slice().sort((a,b)=>b.time-a.time).map(p=>`<article class="feed-item"><div class="feed-head"><div class="initial">${esc((p.name||'OM').split(' ').map(x=>x[0]).join('').slice(0,2))}</div><div><b>${esc(p.name)}</b><small>${fmt(p.time)}</small></div></div><p>${esc(p.body)}</p></article>`).join('');composer.classList.toggle('hidden',!state.user)}
postBody.oninput=e=>count.textContent=`${e.target.value.length}/500`;postBtn.onclick=()=>{if(!state.user){openAuth(true);return}const body=postBody.value.trim();if(!body)return;state.posts.push({id:'p'+Date.now(),name:state.user.name,body,time:Date.now()});award(state.user,'firstPost',10);save();postBody.value='';count.textContent='0/500';renderCommunity();renderHome();renderHeader();toast('Posted — Rank points updated.')};
const mapSeed=[...state.profiles.filter(p=>p.map&&p.city).map(p=>({type:'members',name:p.name,city:p.city,state:p.state,country:p.country})) ,{type:'mosques',name:'Demo Mosque',city:'Minneapolis',state:'MN',country:'United States'},{type:'mosques',name:'Community Mosque',city:'Toronto',state:'ON',country:'Canada'},{type:'events',name:'Welcome Night',city:'Minneapolis',state:'MN',country:'United States'}];
function renderMap(){const q=(mapSearch.value||'').toLowerCase();const type=mapFilter.value;const arr=mapSeed.filter(x=>(type===x.type)&&(!q||[x.name,x.city,x.state,x.country].join(' ').toLowerCase().includes(q)));mapResults.innerHTML=arr.length?arr.map((x,i)=>`<button class="map-result" data-i="${i}"><span class="pulse"></span><b>${esc(x.name)}</b><small>${esc(x.city)}${x.state?', '+esc(x.state):''} · ${esc(x.country)}</small></button>`).join(''):'<p class="muted">No matching locations yet.</p>';mapDots.innerHTML=arr.map((x,i)=>{const pos=[[25,38],[31,48],[44,31],[52,42],[62,35],[70,50],[78,32],[66,65]][i%8];return `<button class="map-dot" style="left:${pos[0]}%;top:${pos[1]}%" title="${esc(x.name)} — ${esc(x.city)}"><span></span></button>`}).join('')};mapSearch.oninput=renderMap;mapFilter.onchange=renderMap;
(async()=>{if(supabaseClient){await hydrateUser()}renderHeader();renderHome();renderEvents();renderCommunity();if(location.hash)go(location.hash.slice(1));else go('home')})();
