import fs from "node:fs";
import path from "node:path";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||""; const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"";
if(!url||!key)throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel environment variables.");
fs.rmSync("dist",{recursive:true,force:true}); fs.mkdirSync("dist/assets/avatars",{recursive:true});
for(const f of ["index.html","styles.css","app.js","home-dashboard-safe.js"])fs.copyFileSync(f,path.join("dist",f));
for(const f of ["emerald.svg","sapphire.svg","amber.svg","onyx.svg","ruby.svg","pearl.svg"])fs.copyFileSync(`assets/avatars/${f}`,path.join("dist/assets/avatars",f));
let html=fs.readFileSync("dist/index.html","utf8");
if(!html.includes('src="home-dashboard.js"'))html=html.replace("</body>",`<script src="home-dashboard.js"></script>\n</body>`);
fs.writeFileSync("dist/index.html",html);fs.writeFileSync("dist/config.js",`window.APP_CONFIG=${JSON.stringify({SUPABASE_URL:url,SUPABASE_ANON_KEY:key})};\n`);fs.renameSync("dist/home-dashboard-safe.js","dist/home-dashboard.js");console.log("Built core E Secure Community + safe Home dashboard into dist/");
