/* OneMuslim Community Service v3 — communities are sub-profiles owned by authenticated users. */
(function(){
  'use strict';
  const shared=()=>window.supabaseClient||window.sb||null;
  const cfg=()=>window.APP_CONFIG||{};
  const client=()=>shared()||(window.supabase?.createClient&&cfg().SUPABASE_URL?window.supabase.createClient(cfg().SUPABASE_URL,cfg().SUPABASE_ANON_KEY):null);
  async function listCommunities(limit=100){const sb=client();if(!sb)return {data:[],error:new Error('Community service unavailable')};return sb.from('communities').select('id,name,slug,description,creator_id,created_at,updated_at').order('name').limit(limit);}
  async function myCommunities(){const sb=client();if(!sb)return {data:[],error:new Error('Community service unavailable')};const {data:{user}}=await sb.auth.getUser();if(!user)return {data:[],error:new Error('Not authenticated')};return sb.from('communities').select('id,name,slug,description,creator_id,created_at,updated_at').eq('creator_id',user.id).order('created_at');}
  async function refreshEditor(select){if(!select)return;try{const {data,error}=await listCommunities();if(error)throw error;const current=select.value;select.innerHTML=['<option value="">Select a community</option>',...(data||[]).map(c=>`<option value="${c.id}" data-community-name="${String(c.name).replace(/"/g,'&quot;')}">${String(c.name).replace(/[&<>]/g,'')}</option>`),'<option value="__create__">＋ Create a Community</option>'].join('');if((data||[]).some(c=>c.id===current))select.value=current;}catch(e){console.warn('Community discovery unavailable',e);}}
  async function requestJoin(communityId,status){const sb=client();if(!sb)throw new Error('Community service unavailable');if(!communityId||communityId==='__create__')return null;if(status)status.textContent='Sending membership request…';const {data,error}=await sb.rpc('request_community_membership',{p_community_id:communityId});if(error)throw error;if(status)status.textContent='Join request sent. The community creator will receive it.';return data;}
  async function pendingRequests(communityId){const sb=client();if(!sb)throw new Error('Community service unavailable');const {data,error}=await sb.from('community_members').select('community_id,user_id,role,status,created_at,updated_at').eq('community_id',communityId).eq('status','pending').order('created_at');if(error)throw error;return data||[];}
  async function respond(communityId,userId,approved){const sb=client();if(!sb)throw new Error('Community service unavailable');const {data,error}=await sb.rpc('respond_to_community_join_request',{p_community_id:communityId,p_user_id:userId,p_approved:approved});if(error)throw error;return data;}
  function wire(){const select=document.getElementById('pbGroup');if(!select||select.dataset.liveCommunity==='3')return;select.dataset.liveCommunity='3';refreshEditor(select);const status=document.getElementById('pbCommunityStatus');let request=document.getElementById('pbRequestJoin');if(!request){request=document.createElement('button');request.type='button';request.className='om-pb-btn';request.id='pbRequestJoin';request.textContent='Request to Join';const create=document.getElementById('pbCreateCommunity');(create||select).insertAdjacentElement('afterend',request);}request.onclick=()=>requestJoin(select.value,status).catch(e=>{if(status)status.textContent=e.message||'Unable to send request.'});const sync=()=>{request.hidden=!select.value||select.value==='__create__';};select.addEventListener('change',sync);sync();}
  function init(){wire();new MutationObserver(wire).observe(document.body,{childList:true,subtree:true});}
  window.OneMuslimCommunityService=Object.freeze({listCommunities,myCommunities,refreshEditor,requestJoin,pendingRequests,respond});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();