(function(){
  var link=document.createElement("link");link.rel="stylesheet";link.href="dashboard-theme.css";document.head.appendChild(link);
  document.body.classList.add("dashboard-theme");
  var publicView=document.getElementById("publicView");if(!publicView)return;
  var dash=document.createElement("section");dash.className="community-dashboard";dash.id="communityDashboard";
  dash.innerHTML='<aside class="dashboard-sidebar"><div class="dash-brand"><span class="dash-logo">E</span><div>eSecure<small>PRIVATE COMMUNITY</small></div></div><nav class="dash-nav"><button class="active" data-go="home"><span>⌂</span>Home</button><button data-go="people"><span>◉</span>People</button><button data-go="profile"><span>◎</span>My Profile</button><button data-go="notes"><span>✦</span>Private Notes</button><button data-go="lessons"><span>★</span>Lessons</button></nav><div class="dash-profile"><i>ES</i><div><small>Welcome to</small><b>eSecure Community</b></div></div></aside><main class="dashboard-main"><div class="dashboard-utility"><input class="dash-search" aria-label="Search" placeholder="⌕  Search community..."><button class="utility-button help">? &nbsp; Help</button><button class="utility-button notice" aria-label="Notifications">♧</button><button class="utility-button" aria-label="Account">◉</button></div><section class="dashboard-hero"><div class="hero-copy"><div class="tiny">PRIVATE • SECURE • CONNECTED</div><h1>Welcome to<br>eSecure Community</h1><p>Your people. Your space. Build your profile, share ideas, learn together, and keep your community behind the lock.</p><button class="dash-cta" data-auth="login">Enter your space &nbsp; →</button></div><div class="hero-orbit"><div class="orbit-ring"></div><div class="hero-emblem">E</div><div class="orbit-chip chip-one">✦ Private by design</div><div class="orbit-chip chip-two">🔒 Member-only</div></div></section><section class="dash-cards"><article class="dash-card learn"><i>◉</i><h2>Community</h2><p>Share thoughtful posts and connect with fellow members.</p></article><article class="dash-card people"><i>♧</i><h2>People</h2><p>Discover voices, interests, and people in your space.</p></article><article class="dash-card profile"><i>◎</i><h2>My Profile</h2><p>Shape the member profile you want others to know.</p></article><article class="dash-card notes"><i>✦</i><h2>Private Notes</h2><p>Keep your thoughts secure and close at hand.</p></article><article class="dash-card lessons"><i>★</i><h2>Lessons</h2><p>Learn, grow, and earn XP through guided prompts.</p></article></section><section class="activity-panel"><div class="activity-title"><span>↗ &nbsp; Today’s Activity</span><button data-auth="signup">Join eSecure &nbsp; →</button></div><div class="activity-row"><div class="activity-stat"><i>♧</i><div><b>24</b><span>Community<br>Members</span></div></div><div class="activity-stat"><i>✓</i><div><b>21</b><span>Members<br>Active today</span></div></div><div class="activity-stat"><i>✦</i><div><b>12</b><span>Ideas & notes<br>Shared today</span></div></div><div class="activity-stat"><i>★</i><div><b>8</b><span>Lessons<br>In progress</span></div></div></div></section></main>';
  publicView.insertBefore(dash,publicView.firstChild);
  function openExisting(id){var btn=document.getElementById(id);if(btn)btn.click();}
  dash.querySelectorAll("[data-auth]").forEach(function(b){b.addEventListener("click",function(){openExisting(this.dataset.auth==="signup"?"openSignup":"openLogin");});});
  dash.querySelectorAll(".dash-card").forEach(function(card){card.addEventListener("click",function(){openExisting("openLogin");});card.style.cursor="pointer";});
  dash.querySelectorAll(".dash-nav button").forEach(function(b){b.addEventListener("click",function(){dash.querySelectorAll(".dash-nav button").forEach(function(x){x.classList.remove("active");});b.classList.add("active");if(b.dataset.go!=="home")openExisting("openLogin");});});
})();