(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const layers=$$('.layer'), scenes=$$('.scene'), dots=$$('.progress span');
const stars=$('#landingStars'), ctx=stars.getContext('2d'); let w=0,h=0,points=[],scrollTarget=scrollY,smooth=scrollY;
function resize(){const d=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;stars.width=w*d;stars.height=h*d;stars.style.width=w+'px';stars.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);points=Array.from({length:Math.min(260,Math.max(100,Math.floor(w*h/6000)))},()=>({x:Math.random()*w,y:Math.random()*h,z:.1+Math.random()*.9,r:.35+Math.random()*1.2,a:.2+Math.random()*.7,p:Math.random()*6.28}));}
function frame(){smooth+=(scrollTarget-smooth)*.065;layers.forEach(el=>{const speed=Number(el.dataset.speed||0);const rect=el.closest('.scene')?.getBoundingClientRect();if(!rect)return;const offset=(innerHeight/2-(rect.top+rect.height/2))*speed*.16;el.style.transform=`translate3d(0,${offset}px,0)`});ctx.clearRect(0,0,w,h);points.forEach(s=>{const y=(s.y-(smooth*.11*s.z)%h+h)%h,x=(s.x+Math.sin(s.p+smooth*.0004)*s.z*12+w)%w;ctx.globalAlpha=s.a*(.35+.65*s.z);ctx.fillStyle='#fff3c9';ctx.beginPath();ctx.arc(x,y,s.r*s.z+.2,0,6.283);ctx.fill()});ctx.globalAlpha=1;requestAnimationFrame(frame)}
addEventListener('scroll',()=>scrollTarget=scrollY,{passive:true});addEventListener('resize',resize);const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=scenes.indexOf(e.target);dots.forEach((d,n)=>d.classList.toggle('active',n===i));}}),{threshold:.55});scenes.forEach(s=>observer.observe(s));
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
const overlay=$('#authOverlay'), form=$('#authForm'), modeSwitch=$('#authSwitch'), title=$('#authTitle'), sub=$('#authSub'), submit=$('#authSubmit'), error=$('#authError'); let mode='login';
function openAuth(next='login'){mode=next;title.textContent=mode==='login'?'Welcome back.':'Begin your journey.';sub.textContent=mode==='login'?'Sign in to continue your journey.':'Create your OneMuslim account.';submit.textContent=mode==='login'?'SIGN IN':'CREATE ACCOUNT';modeSwitch.textContent=mode==='login'?'New here? Create an account':'Already have an account? Sign in';error.textContent='';overlay.classList.remove('hidden');document.body.style.overflow='hidden';$('#authEmail').focus()}
function closeAuth(){overlay.classList.add('hidden');document.body.style.overflow=''}
$('#signInBtn').onclick=()=>openAuth('login');$('#joinBtn').onclick=()=>openAuth('signup');$('#authClose').onclick=closeAuth;overlay.addEventListener('click',e=>{if(e.target===overlay)closeAuth()});modeSwitch.onclick=()=>openAuth(mode==='login'?'signup':'login');
form.addEventListener('submit',async e=>{e.preventDefault();error.textContent='';const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const client=window.OneMuslimSupabaseClient?.getClient?.();if(!client){error.textContent='Authentication is unavailable right now.';return}submit.disabled=true;try{let result=mode==='login'?await client.auth.signInWithPassword({email,password}):await client.auth.signUp({email,password});if(result.error)throw result.error;if(mode==='signup'&&!result.data.session){error.textContent='Account created. Check your email to confirm, then sign in.';return}closeAuth();window.location.href='index.html#profile'}catch(err){error.textContent=err.message||'Unable to authenticate.'}finally{submit.disabled=false}});
async function syncSession(){const client=window.OneMuslimSupabaseClient?.getClient?.();if(!client)return;const {data}=await client.auth.getSession();const user=data?.session?.user;if(!user)return;$('#signInBtn').classList.add('hidden');$('#joinBtn').classList.add('hidden');const avatar=$('#profileBtn');avatar.classList.remove('hidden');const url=user.user_metadata?.avatar_url||user.user_metadata?.avatarUrl||user.user_metadata?.picture;if(url)avatar.style.backgroundImage=`url(${JSON.stringify(url)})`;else avatar.textContent=(user.user_metadata?.display_name||user.email||'U').slice(0,1).toUpperCase();avatar.onclick=()=>window.location.href='index.html#profile'}
if($('#skyLearn'))$('#skyLearn').onclick=()=>$('#sky').scrollIntoView({behavior:'smooth'});resize();frame();syncSession();
})();
