/* OneMuslim navigation: desktop top navigation, mobile drawer, Back + Home. */
(function(){
  function clearViewedProfile(){
    const page=document.getElementById('profilePage');
    if(page){page.dataset.profileMode='my-profile';delete page.dataset.profileUserId;delete page.dataset.omViewedRendered;}
    if(new URLSearchParams(location.search).has('profile'))history.replaceState({},'',location.pathname+location.hash);
    window.OneMuslimViewedProfileRoute?.leave?.();
  }
  function loadScript(id,src){return new Promise((resolve,reject)=>{const existing=document.getElementById(id);if(existing){if(window.OneMuslimShop&&id==='oneMuslimShopScript')return resolve();if(existing.dataset.omLoaded==='1')return resolve();existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.id=id;s.src=src;s.defer=true;s.onload=()=>{s.dataset.omLoaded='1';resolve()};s.onerror=reject;document.body.appendChild(s)})}
  function openShop(){
    return loadScript('oneMuslimShopScript','shop-page.js?v=20260913-02').then(()=>{
      if(window.OneMuslimShop?.show){window.OneMuslimShop.show();return true}
      throw new Error('OneMuslimShop did not initialize');
    }).catch(e=>{console.warn('OneMuslim Shop:',e);return false});
  }
  function wireApp(){const app=document.getElementById('appView');if(!app)return;const links=[...app.querySelectorAll('.app-nav-link[data-page]')],sides=[...app.querySelectorAll('.side[data-page]')],menu=document.getElementById('appMenuToggle'),sidebar=document.getElementById('mobileAppSidebar'),back=document.getElementById('appBack');if(!app.dataset.navWired){app.dataset.navWired='1';let current='feed',stack=[],goingBack=false;const show=(page,push=true)=>{if(page==='coming-soon'){window.location.href='coming-soon.html';return}if(page!=='profile')clearViewedProfile();if(page==='shop'){if(push&&!goingBack&&current!==page)stack.push(current);openShop();current=page;links.forEach(b=>b.classList.toggle('active',b.dataset.page===page));sides.forEach(b=>b.classList.toggle('active',b.dataset.page===page));sidebar?.classList.remove('open');return}if(page==='communities'&&window.OneMuslimCommunities){if(push&&!goingBack&&current!==page)stack.push(current);window.OneMuslimCommunities.show();current=page;links.forEach(b=>b.classList.toggle('active',b.dataset.page===page));sides.forEach(b=>b.classList.toggle('active',b.dataset.page===page));sidebar?.classList.remove('open');return}const target=sides.find(b=>b.dataset.page===page);if(target){if(push&&!goingBack&&current!==page)stack.push(current);target.click()}else window.OneMuslimPlatform?.showPage(page);current=page;links.forEach(b=>b.classList.toggle('active',b.dataset.page===page));sidebar?.classList.remove('open')};sides.forEach(b=>b.addEventListener('click',()=>{current=b.dataset.page||'feed';if(current!=='profile')clearViewedProfile();if(current==='shop')openShop();if(current==='communities'&&window.OneMuslimCommunities)window.OneMuslimCommunities.show();links.forEach(x=>x.classList.toggle('active',x.dataset.page===current));sides.forEach(x=>x.classList.toggle('active',x.dataset.page===current));sidebar?.classList.remove('open')}));links.forEach(b=>b.addEventListener('click',()=>show(b.dataset.page||'feed',true)));menu?.addEventListener('click',()=>sidebar?.classList.toggle('open'));back?.addEventListener('click',()=>{const previous=stack.pop()||'feed';goingBack=true;show(previous,false);goingBack=false});document.addEventListener('click',e=>{if(sidebar?.classList.contains('open')&&!sidebar.contains(e.target)&&e.target!==menu)sidebar.classList.remove('open')})}}
  function wirePublic(){const home=document.querySelector('.social-home');if(!home||home.dataset.mobileNav==='1')return;home.dataset.mobileNav='1';const top=home.querySelector('.social-top'),sidebar=home.querySelector('.social-sidebar');if(!top||!sidebar)return;const button=document.createElement('button');button.className='social-mobile-menu-btn';button.type='button';button.setAttribute('aria-label','Open navigation');button.textContent='☰';top.insertBefore(button,top.firstChild);const drawer=document.createElement('div');drawer.className='mobile-social-menu';drawer.innerHTML='<div class="mobile-menu-title">OneMuslim</div>';sidebar.querySelectorAll('.social-nav button').forEach(original=>{const b=document.createElement('button');b.type='button';b.innerHTML=original.innerHTML;b.addEventListener('click',()=>original.click());drawer.appendChild(b)});const coming=document.createElement('button');coming.type='button';coming.textContent='Coming Soon';coming.addEventListener('click',()=>window.location.href='coming-soon.html');drawer.appendChild(coming);home.appendChild(drawer);button.addEventListener('click',()=>drawer.classList.toggle('open'));document.addEventListener('click',e=>{if(drawer.classList.contains('open')&&!drawer.contains(e.target)&&e.target!==button)drawer.classList.remove('open')})}
  function addShopNav(){if(document.querySelector('[data-page="shop"]'))return;const top=document.querySelector('#appView .app-nav-links');const side=document.querySelector('#appView .sidebar nav');if(top){const b=document.createElement('button');b.type='button';b.className='app-nav-link';b.dataset.page='shop';b.textContent='Shop';const before=top.querySelector('.om-coming-soon-nav');before?top.insertBefore(b,before):top.appendChild(b)}if(side){const b=document.createElement('button');b.type='button';b.className='side';b.dataset.page='shop';b.textContent='🛍 Shop';const before=side.querySelector('.om-coming-soon-nav');before?side.insertBefore(b,before):side.appendChild(b)}}
  function init(){loadScript('oneMuslimPlatformScript','one-muslim-platform.js');loadScript('oneMuslimProfileBuilderScript','profile-builder.js');loadScript('oneMuslimPublicNavigationScript','public-platform-navigation.js');loadScript('oneMuslimShopScript','shop-page.js?v=20260913-02').catch(()=>{});addShopNav();wireApp();wirePublic();const observer=new MutationObserver(()=>{addShopNav();wireApp();wirePublic()});observer.observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
/* NAV V2 */
(function(){'use strict';
const G=[['Explore',[['public-home','⌂','Home','Your One Muslim home'],['feed','◉','Community Feed','Posts and conversations'],['communities','◇','Communities','Groups and spaces'],['profiles','◉','People','Discover members']]],['Learn & Grow',[['lessons','★','Lessons','Learn and earn XP'],['newsletter','📰','Newsletter','Read the latest edition']]],['Your Space',[['profile','◎','My Profile','Your identity and activity']]],['Tools & More',[['hudhud','🐦','HudHud AI','Your AI companion'],['shop','🛍','Shop','One Muslim collection'],['coming-soon','✦','Coming Soon','What is next']]],['Administration',[['admin','⚙','Admin Console','Platform controls']]]];
function boot(){const app=document.getElementById('appView');if(!app||document.getElementById('omNav2'))return;const n=document.createElement('div');n.id='omNav2';n.className='om-nav2';n.innerHTML='<div class="om-nav2-brand"><img src="assets/won-muslim-logo.svg" alt=""><span>ONE MUSLIM</span></div><button id="omNav2Open" class="om-nav2-trigger">☰ <span>Navigate</span><small>All areas</small></button>';app.prepend(n);const o=document.createElement('div');o.className='om-nav2-overlay';const p=document.createElement('aside');p.className='om-nav2-panel';p.innerHTML='<div class="om-nav2-panel-head"><strong>One Muslim</strong><button class="om-nav2-close">×</button></div><input id="omNav2Search" class="om-nav2-search" placeholder="Search navigation…"><div id="omNav2Groups"></div><div class="om-nav2-footer"><button id="omNav2Signout" class="danger">Sign out</button><button class="om-nav2-close2">Close</button></div>';document.body.append(o,p);const h=p.querySelector('#omNav2Groups'),close=()=>{o.classList.remove('open');p.classList.remove('open')},open=()=>{o.classList.add('open');p.classList.add('open')};function render(q=''){h.innerHTML='';G.forEach(g=>{const a=g[1].filter(x=>(x[2]+' '+x[3]).toLowerCase().includes(q.toLowerCase()));if(!a.length)return;const s=document.createElement('section');s.className='om-nav2-group';s.innerHTML='<div class="om-nav2-group-title">'+g[0]+'</div><div class="om-nav2-items"></div>';a.forEach(x=>{const b=document.createElement('button');b.className='om-nav2-item';b.innerHTML='<span class="om-nav2-icon">'+x[1]+'</span><span class="om-nav2-copy"><b>'+x[2]+'</b><span>'+x[3]+'</span></span>';b.onclick=()=>{if(x[0]==='communities')window.OneMuslimCommunities?.show?.();else if(x[0]==='newsletter')location.href='newsletter.html';else if(x[0]==='hudhud')location.href='hudhud-ai.html';else if(x[0]==='coming-soon')location.href='coming-soon.html';else if(x[0]==='admin')document.getElementById('omAdminNav')?.click();else app.querySelector('[data-page="'+x[0]+'"]')?.click();close()};s.querySelector('.om-nav2-items').append(b)});h.append(s)})}document.getElementById('omNav2Open').onclick=open;p.querySelector('.om-nav2-close').onclick=close;p.querySelector('.om-nav2-close2').onclick=close;o.onclick=close;p.querySelector('#omNav2Search').oninput=e=>render(e.target.value);p.querySelector('#omNav2Signout').onclick=()=>document.getElementById('signOut')?.click();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();new MutationObserver(boot).observe(document.body,{childList:true,subtree:true});})();
