/* OneMuslim homepage — single-world layered parallax journey. */
(function(){'use strict';
const reduce=matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const p=new URLSearchParams(location.search);const flow=(p.get('flow')||p.get('journey')||p.get('ref')||location.hash||'').toLowerCase();const revert=/revert|shahada|new[-_ ]?muslim/.test(flow);
let i=0,name='',mode='fun',journey;
const copy=[
()=>`<span class="omj-kicker">${revert?'A NEW BEGINNING':'WELCOME TO ONE MUSLIM'}</span><h1>One Muslim<br><em>One <span class="omj-glow-word">Allah</span></em></h1><div class="omj-divine-word">الله</div><p>${revert?'Did you just take your Shahada?':'Is this your first time here?'}</p><div class="omj-actions"><button class="omj-btn primary" data-action="yes">Yes</button><button class="omj-btn" data-action="no">No</button></div>`,
()=>`<span class="omj-kicker">YOUR JOURNEY</span><h2>Want to learn<br><em>in a fun way?</em></h2><p>Learn through interactive lessons, notes, community and structured courses — at your pace.</p><div class="omj-actions"><button class="omj-btn primary" data-action="fun">Yes — make it fun</button><button class="omj-btn" data-action="serious">Serious only</button></div>`,
()=>mode==='serious'?`<span class="omj-kicker">SERIOUS MODE</span><h2>Before we begin,<br><em>do we agree?</em></h2><p>Learn sincerely. Ask difficult questions. Pursue truth. Treat people with respect.</p><div class="omj-actions"><button class="omj-btn primary" data-action="agree">I agree →</button></div>`:`<span class="omj-kicker">LET'S BEGIN</span><h2>Let's get<br><em>started.</em></h2><p>You don't have to know everything. Start where you are. Keep asking. Keep seeking.</p><div class="omj-actions"><button class="omj-btn primary" data-action="next">Continue →</button></div>`,
()=>`<span class="omj-kicker">ONE MUSLIM</span><h2>You are part of<br><em>a big community.</em></h2><p>Profiles, conversations, people, posts and shared knowledge — you're not learning alone.</p><div class="omj-feature-card"><strong>One Muslim Community</strong><span>Connect · learn · share · grow together.</span></div><div class="omj-actions"><button class="omj-btn primary" data-action="next">Next →</button></div>`,
()=>`<span class="omj-kicker">KEEP WHAT YOU LEARN</span><h2>Meet <em>My Notes.</em></h2><p>Keep verses, questions, lessons and ideas beside you while you learn.</p><div class="omj-note-demo"><b>My Notes</b><p>Write down what you want to remember. Come back to it whenever you need it.</p></div><div class="omj-actions"><button class="omj-btn primary" data-action="next">Next →</button></div>`,
()=>`<span class="omj-kicker">ONE UNIVERSITY</span><h2>Your learning<br><em>starts here.</em></h2><p>Courses, lessons and structured learning — designed to help you keep growing.</p><div class="omj-feature-card"><strong>One University</strong><span>Explore courses · follow lessons · build knowledge.</span></div><div class="omj-actions"><button class="omj-btn primary" data-action="next">Get started →</button></div>`,
()=>`<span class="omj-kicker">ONE MUSLIM</span><div class="omj-final-mark">الله</div><h2>Your journey begins.</h2><p>Learn. Reflect. Connect. Grow.</p><div class="omj-actions"><button class="omj-btn primary" data-action="enter">Enter One Muslim →</button><button class="omj-btn" data-action="signup">Create account</button><button class="omj-btn" data-action="login">Sign in</button></div>`
];
function auth(type){document.getElementById(type==='signup'?'openSignup':'openLogin')?.click();window.showAuth?.(type)}
function enter(){journey?.classList.add('hidden');document.getElementById('publicView')?.classList.add('hidden');const a=document.getElementById('appView');if(a){a.classList.remove('hidden');a.querySelector('[data-page="public-home"]')?.click()}}
function build(){if($('#omJourney'))return;journey=document.createElement('div');journey.id='omJourney';journey.innerHTML=`<div class="omj-topbar"><div class="omj-brand"><span class="omj-brand-mark">1</span><span>ONE MUSLIM</span></div><div class="omj-status" id="omjStatus">WELCOME</div></div><div class="omj-progress" id="omjProgress"></div><main class="omj-stage"><section class="omj-scene active"><div class="omj-layer omj-earth-photo" data-depth=".04"></div><div class="omj-layer omj-particles" data-depth=".18"></div><div class="omj-layer omj-atmosphere" data-depth=".30"></div><div class="omj-layer omj-clouds" data-depth=".62"></div><div class="omj-copy" id="omjCopy"></div></section></main><div class="omj-footer-hint">Tap to continue · Move to feel the depth</div></div>`;document.body.appendChild(journey);const dots=$('#omjProgress');for(let n=0;n<copy.length;n++){const b=document.createElement('button');b.type='button';b.onclick=()=>{if(n<=i+1){i=n;render()}};dots.appendChild(b)}render();if(!reduce)pointer()}
function render(){const host=$('#omjCopy');if(!host)return;const old=host.querySelector('.omj-view');const v=document.createElement('div');v.className='omj-view';v.innerHTML=copy[i]();if(old){old.classList.add('is-leaving');setTimeout(()=>{old.remove();host.appendChild(v);wire(v)},reduce?0:320)}else{host.appendChild(v);wire(v)}document.querySelectorAll('#omjProgress button').forEach((b,n)=>b.classList.toggle('active',n===i));$('#omjStatus').textContent=i===6?'READY TO ENTER':`JOURNEY ${String(i+1).padStart(2,'0')} / 07`}
function next(){if(i<6){i++;render()}}
function wire(root){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='yes'){if(revert){renderName()}else{i=1;render()}}else if(a==='no'){i=1;render()}else if(a==='fun'){mode='fun';i=2;render()}else if(a==='serious'){mode='serious';i=2;render()}else if(a==='agree'||a==='next'){next()}else if(a==='enter'){enter()}else if(a==='signup'||a==='login'){auth(a)}})}
function renderName(){const h=$('#omjCopy');h.innerHTML=`<div class="omj-view"><span class="omj-kicker">WELCOME, NEW MUSLIM</span><h2>What is your name?</h2><p>We will use it to make this moment personal.</p><input class="omj-name" id="omjName" placeholder="Your name" maxlength="60" autocomplete="name"><div class="omj-actions"><button class="omj-btn primary" id="omjNameGo">Continue →</button></div></div>`;$('#omjNameGo').onclick=()=>{const v=$('#omjName')?.value.trim();if(!v)return $('#omjName')?.focus();name=v;h.innerHTML=`<div class="omj-view"><span class="omj-kicker">WELCOME HOME</span><div class="omj-final-mark omj-name-mark">${esc(name)}</div><h2>Welcome. Congratulations.</h2><p>You have taken a beautiful step. May Allah make your path clear, steady, and full of peace.</p><div class="omj-actions"><button class="omj-btn primary" data-action="next">Continue →</button></div></div>`;wire(h.querySelector('.omj-view'))}}
function pointer(){let x=0,y=0,raf=0;addEventListener('pointermove',e=>{x=e.clientX/innerWidth-.5;y=e.clientY/innerHeight-.5;if(raf)return;raf=requestAnimationFrame(()=>{raf=0;document.querySelectorAll('#omJourney [data-depth]').forEach(l=>{const d=+l.dataset.depth;l.style.transform=`translate3d(${x*d*-42}px,${y*d*-28}px,0) scale(${1+d*.035})`})})},{passive:true});let lock=0;addEventListener('wheel',e=>{if(lock||Math.abs(e.deltaY)<8)return;lock=1;e.deltaY>0?next():i>0&&(i--,render());setTimeout(()=>lock=0,700)},{passive:true})}
async function boot(){if(!document.getElementById('publicView'))return;build();const s=await window.OneMuslimSupabaseClient?.getClient?.()?.auth.getSession().catch(()=>({data:{session:null}}));if(s?.data?.session)$('#omjStatus').textContent='SECURE SESSION'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
})();
