/* OneMuslim Profile Builder v3 — mobile-first editor with gender-aware Platinum avatars. */
(function(){
  'use strict';
  const groups=['Islamic Society','Apologetics','Da’wah','Qur’an Study','Tafsir Circle','Hadith Study','Tajweed','The Belt Boys','Torah Boys'];
  const backgrounds=[['Islamic Geometry','linear-gradient(135deg,#fbf5e8,#f1e6cf)'],['Mosque Silhouette','linear-gradient(135deg,#f7ecd6,#ead8b5)'],['Islamic Arch','linear-gradient(135deg,#f8f2e5,#e9dfcc)'],['Crescent & Stars','linear-gradient(135deg,#0e2d27,#193f35)'],['Luxury Gold','linear-gradient(135deg,#fff8e8,#d8b66a)'],['Emerald','linear-gradient(135deg,#0d4b3d,#1f6b57)'],['Dark Mosque','linear-gradient(135deg,#061e1a,#173a31)'],['Minimal Cream','linear-gradient(135deg,#fffdf8,#f4f0e7)']];
  const accents=[['emerald','#1f6a55'],['gold','#c89d3c'],['navy','#243b62'],['plum','#70536f'],['ruby','#a34d52']];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const sys=()=>window.OneMuslimProfileSystem;
  function normalized(){return sys()?.normalize(window.profile||{})||{...(window.profile||{})};}
  function xp(){return sys()?.xpOf(normalized())||0;}
  function platinumUnlocked(){return xp()>=10000;}
  function open(){
    const p=normalized(), o=document.createElement('div');o.className='om-pb-overlay';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');
    const platinum=platinumUnlocked();
    o.innerHTML=`<section class="om-pb-shell"><header class="om-pb-top"><div><span class="om-pb-kicker">ONE MUSLIM · PROFILE</span><h2>Edit your profile</h2></div><button class="om-pb-close" aria-label="Close">×</button></header>
    <nav class="om-pb-tabs" aria-label="Profile editor sections"><button class="om-pb-tab active" data-tab="avatar">◉<small>Avatar</small></button><button class="om-pb-tab" data-tab="background">▧<small>Background</small></button><button class="om-pb-tab" data-tab="style">✦<small>Personalize</small></button><button class="om-pb-tab" data-tab="profile">◎<small>Profile</small></button><button class="om-pb-tab" data-tab="privacy">⌁<small>Privacy</small></button></nav>
    <main class="om-pb-main"><div class="om-pb-preview"><div class="om-pb-preview-banner" id="pbPreviewBanner"></div><div class="om-pb-preview-body"><div class="om-pb-preview-avatar" id="pbPreviewAvatar"></div><div class="om-pb-preview-name">${esc(p.display_name||p.full_name||'Your Name')}</div><div class="om-pb-preview-meta">@${esc(p.username||'username')} · ${esc(p.profile_title||'Muslim')}</div><div class="om-pb-preview-stats"><span><b>${xp().toLocaleString()}</b> XP</span><span><b>${esc(p.group_team||'—')}</b> Group</span></div></div></div>
    <section class="om-pb-panel active" data-panel="avatar"><div class="om-pb-heading"><span class="om-pb-kicker">IDENTITY</span><h3>Choose your avatar</h3><p>Choose your gender here. Personalize only shows matching avatar options.</p></div><div class="om-pb-grid"><div class="om-pb-card"><label>Identity</label><div class="om-pb-choices"><button class="om-pb-choice pb-gender ${p.avatar_gender!=='female'?'selected':''}" data-gender="male"><span class="fake-avatar">M</span>Male</button><button class="om-pb-choice pb-gender ${p.avatar_gender==='female'?'selected':''}" data-gender="female"><span class="fake-avatar">F</span>Female</button></div></div></div></section>
    <section class="om-pb-panel" data-panel="background"><div class="om-pb-heading"><span class="om-pb-kicker">ATMOSPHERE</span><h3>Set your background</h3></div><div class="om-pb-grid">${backgrounds.map((b,i)=>`<button class="om-pb-card om-pb-bg ${p.profile_background===(i===0?'default':b[0])?'selected':''}" data-bg="${esc(i===0?'default':b[0])}" style="background:${b[1]}"><strong>${b[0]}</strong></button>`).join('')}</div></section>
    <section class="om-pb-panel" data-panel="style"><div class="om-pb-heading"><span class="om-pb-kicker">PERSONALIZE</span><h3>Make it yours</h3><p>Premium avatars replace your original avatar when selected.</p></div><div class="om-pb-card"><label>Avatar finish</label><div class="om-pb-choices"><button class="om-pb-choice pb-package ${p.avatar_package==='default'?'selected':''}" data-package="default"><span class="fake-avatar">◉</span>Original</button><button class="om-pb-choice pb-package platinum-choice ${p.avatar_package==='platinum_package'?'selected':''} ${platinum?'':'locked'}" data-package="platinum_package" ${platinum?'':'disabled'}><img class="pb-platinum-thumb" src="${p.avatar_gender==='female'?'assets/avatars/platinum-female.PNG':'assets/avatars/platinum-male.PNG'}" alt="Platinum ${p.avatar_gender==='female'?'female':'male'} avatar">Platinum${platinum?'':' 🔒'}</button></div><div class="om-pb-note">Platinum unlocks at 10,000 XP. ${platinum?'Unlocked.':'You need '+Math.max(0,10000-xp()).toLocaleString()+' more XP.'}</div></div><div class="om-pb-card" style="margin-top:14px"><label>Accent color</label><div class="om-pb-swatches">${accents.map(a=>`<button class="om-pb-swatch ${p.profile_accent===a[0]?'selected':''}" data-accent="${a[0]}" style="background:${a[1]}" aria-label="${a[0]}"></button>`).join('')}</div></div></section>
    <section class="om-pb-panel" data-panel="profile"><div class="om-pb-heading"><span class="om-pb-kicker">PROFILE DETAILS</span><h3>Tell the community</h3></div><div class="om-pb-grid"><div class="om-pb-card"><label>Group or team</label><select class="om-pb-select" id="pbGroup"><option value="">No group selected</option>${groups.map(g=>`<option value="${esc(g)}" ${p.group_team===g?'selected':''}>${esc(g)}</option>`).join('')}</select></div><div class="om-pb-card"><label>Bio</label><textarea class="om-pb-select" id="pbBio" rows="4" placeholder="Tell the community about yourself">${esc(p.bio||'')}</textarea></div></div></section>
    <section class="om-pb-panel" data-panel="privacy"><div class="om-pb-heading"><span class="om-pb-kicker">CONTROL</span><h3>Privacy & visibility</h3></div><div class="om-pb-card"><label>Profile visibility</label><select class="om-pb-select" id="pbPrivacy"><option value="public" ${p.profile_visibility!=='private'?'selected':''}>Public — discoverable</option><option value="private" ${p.profile_visibility==='private'?'selected':''}>Private — hidden from People/Group filters</option></select></div></section>
    <div class="om-pb-actions"><button class="om-pb-btn" id="pbCancel">Cancel</button><button class="om-pb-btn primary" id="pbSave">Save changes</button></div></main></section>`;
    document.body.appendChild(o);let draft={...p};
    const renderAvatar=()=>{const img=o.querySelector('#pbPreviewAvatar'),src=draft.avatar_package==='platinum_package'&&platinumUnlocked()?sys().AVATAR_ASSETS[draft.avatar_gender]:null;if(src)img.innerHTML=`<img src="${src}" alt="Platinum avatar">`;else img.textContent=draft.avatar_gender==='female'?'F':'M';};
    const preview=()=>{const b=backgrounds.find(x=>x[0]===draft.profile_background);o.querySelector('#pbPreviewBanner').style.background=b?b[1]:'linear-gradient(135deg,#f5ead3,#dcebe3)';renderAvatar();};
    const close=()=>o.remove();o.querySelector('.om-pb-close').onclick=close;o.querySelector('#pbCancel').onclick=close;o.addEventListener('click',e=>{if(e.target===o)close()});
    o.querySelectorAll('.om-pb-tab').forEach(t=>t.onclick=()=>{o.querySelectorAll('.om-pb-tab').forEach(x=>x.classList.toggle('active',x===t));o.querySelectorAll('.om-pb-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===t.dataset.tab));});
    o.querySelectorAll('.pb-gender').forEach(b=>b.onclick=()=>{draft.avatar_gender=b.dataset.gender;o.querySelectorAll('.pb-gender').forEach(x=>x.classList.toggle('selected',x===b));if(draft.avatar_package==='platinum_package')draft.avatar_asset=sys().AVATAR_ASSETS[draft.avatar_gender];preview();});
    o.querySelectorAll('.pb-package').forEach(b=>b.onclick=()=>{if(!b.disabled){draft.avatar_package=b.dataset.package;draft.avatar_asset=b.dataset.package==='platinum_package'?sys().AVATAR_ASSETS[draft.avatar_gender]:null;o.querySelectorAll('.pb-package').forEach(x=>x.classList.toggle('selected',x===b));preview();}});
    o.querySelectorAll('.om-pb-bg').forEach(b=>b.onclick=()=>{draft.profile_background=b.dataset.bg;o.querySelectorAll('.om-pb-bg').forEach(x=>x.classList.toggle('selected',x===b));preview();});
    o.querySelectorAll('.om-pb-swatch[data-accent]').forEach(b=>b.onclick=()=>{draft.profile_accent=b.dataset.accent;o.querySelectorAll('[data-accent]').forEach(x=>x.classList.toggle('selected',x===b));});
    o.querySelector('#pbSave').onclick=async()=>{draft.group_team=o.querySelector('#pbGroup').value;draft.bio=o.querySelector('#pbBio').value.trim();draft.profile_visibility=o.querySelector('#pbPrivacy').value;if(draft.avatar_package==='platinum_package'&&!platinumUnlocked()){toast?.('Platinum requires 10,000 XP.');return;}window.profile=sys()?.applyUnlocks(draft)||draft;const s=JSON.parse(localStorage.getItem('onemuslim_platform_v1')||'{}');s.profile={...(s.profile||{}),...window.profile};localStorage.setItem('onemuslim_platform_v1',JSON.stringify(s));try{if(window.APP_CONFIG?.SUPABASE_URL&&window.supabase){const sb=window.supabase.createClient(window.APP_CONFIG.SUPABASE_URL,window.APP_CONFIG.SUPABASE_ANON_KEY);await sb.from('profiles').update({gender:draft.avatar_gender,profile_visibility:draft.profile_visibility,bio:draft.bio,avatar_url:draft.avatar_asset}).eq('id',draft.id)}}catch(e){console.warn('Profile persistence unavailable',e)}close();window.OneMuslimPlatform?.refreshFloat?.();};preview();
  }
  function wire(){const b=document.getElementById('editProfile');if(b&&!b.dataset.pbv3){b.dataset.pbv3='1';b.onclick=open;}}
  function init(){wire();new MutationObserver(wire).observe(document.body,{childList:true,subtree:true});} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
