/* OneMuslim public profile modal for People. */
(() => {
  'use strict';
  const cfg=window.APP_CONFIG||{};
  const db=window.supabase?.createClient?.(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  if(!db)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const name=p=>p?.display_name||`${p?.first_name||''} ${p?.last_name||''}`.trim()||'Member';
  const xp=p=>Number(p?.xp_total??p?.xp??p?.rank_points??p?.points??0)||0;
  const cfgOf=p=>p?.avatar_config&&typeof p.avatar_config==='object'?p.avatar_config:{};
  const bgName=p=>String(p?.profile_background||cfgOf(p).background||'default');
  const accent=p=>p?.profile_accent||'#1f6a55';
  const gender=p=>(p?.avatar_gender||cfgOf(p).gender||'male')==='female'?'female':'male';
  const avatar=p=>{const g=gender(p);return xp(p)>=10000?`/assets/avatar/platinum/platinum-${g}.PNG`:`/assets/avatar/base/avatar-master-${g}.jpeg`};
  const backgrounds={'default':'linear-gradient(135deg,#eef4ef,#dfece5)','Islamic Geometry':'linear-gradient(135deg,#fbf5e8,#f1e6cf)','Mosque Silhouette':'linear-gradient(135deg,#f7ecd6,#ead8b5)','Islamic Arch':'linear-gradient(135deg,#f8f2e5,#e9dfcc)','Crescent & Stars':'linear-gradient(135deg,#0e2d27,#193f35)','Luxury Gold':'linear-gradient(135deg,#fff8e8,#d8b66a)','Emerald':'linear-gradient(135deg,#0d4b3d,#1f6b57)','Dark Mosque':'linear-gradient(135deg,#061e1a,#173a31)','Minimal Cream':'linear-gradient(135deg,#fffdf8,#f4f0e7)'};
  function styles(){if(document.getElementById('omProfileModalStyles'))return;const s=document.createElement('style');s.id='omProfileModalStyles';s.textContent=`
    .om-profile-modal-backdrop{position:fixed;inset:0;z-index:99990;background:rgba(10,25,22,.42);backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:22px;box-sizing:border-box}
    .om-profile-modal{width:min(900px,96vw);max-height:min(900px,92vh);overflow:auto;background:#fff;border:1px solid #dbe5df;border-radius:28px;box-shadow:0 28px 90px rgba(0,0,0,.25);position:relative;--om-accent:#1f6a55}
    .om-profile-modal-banner{height:185px;background:var(--om-bg);position:relative;overflow:hidden}
    .om-profile-modal-banner:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(255,255,255,.04),rgba(0,0,0,.14))}
    .om-profile-modal-close{position:absolute;right:16px;top:16px;z-index:5;width:40px;height:40px;border:1px solid rgba(255,255,255,.65);border-radius:50%;background:rgba(255,255,255,.88);color:#18392f;font-size:23px;cursor:pointer}
    .om-profile-modal-label{position:absolute;left:18px;top:18px;z-index:4;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,.82);color:#18392f;font-size:10px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}
    .om-profile-modal-body{padding:0 30px 30px}.om-profile-modal-avatar{width:132px;height:132px;margin-top:-66px;position:relative;z-index:6;border:6px solid #fff;border-radius:50%;overflow:hidden;background:#eef3ef;box-shadow:0 12px 30px rgba(20,45,36,.2)}
    .om-profile-modal-avatar img{width:100%;height:100%;object-fit:cover;object-position:center top}.om-profile-modal-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-top:15px}.om-profile-modal h2{margin:0;color:#18392f;font:700 clamp(28px,5vw,40px)/1.1 Georgia,serif}.om-profile-modal-handle{color:#708078;margin-top:4px;font-size:13px}.om-profile-modal-bio{color:#52645d;line-height:1.55;margin:12px 0 0;max-width:680px}.om-profile-modal-actions{display:flex;gap:8px}.om-profile-modal-actions button{border:1px solid #d7e2dc;background:#f2f6f3;color:#185f55;border-radius:12px;padding:10px 15px;font-weight:850;cursor:pointer;white-space:nowrap}.om-profile-modal-actions .follow{background:var(--om-accent);border-color:var(--om-accent);color:#fff}.om-profile-modal-chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:16px}.om-profile-modal-chip{padding:7px 10px;border-radius:999px;background:#f4f7f5;border:1px solid #dfe8e2;color:#51655d;font-size:11px;font-weight:750}.om-profile-modal-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.om-profile-modal-stat{padding:15px;border-radius:16px;background:#f8faf8;border:1px solid #e1e9e3}.om-profile-modal-stat b{display:block;color:#18392f;font-size:21px}.om-profile-modal-stat span{font-size:10px;color:#718078;text-transform:uppercase;letter-spacing:.06em}.om-profile-modal-theme{margin-top:12px;padding:15px 16px;border-radius:16px;background:color-mix(in srgb,var(--om-accent) 7%,#fff);border:1px solid color-mix(in srgb,var(--om-accent) 18%,#e3e9e4);color:#5d7068;font-size:12px}.om-profile-modal-posts{margin-top:18px;border-top:1px solid #e4ebe6;padding-top:16px}.om-profile-modal-posts h3{margin:0 0 10px;color:#18392f}.om-profile-modal-post{padding:12px 14px;border:1px solid #e2e9e5;border-radius:14px;margin-top:8px;color:#52645d;background:#fbfcfb}.om-profile-modal-empty{color:#7a8982;font-size:13px}.om-profile-modal-loading{padding:60px;text-align:center;color:#52645d}
    @media(max-width:650px){.om-profile-modal-backdrop{padding:8px}.om-profile-modal{max-height:96vh;border-radius:22px}.om-profile-modal-banner{height:150px}.om-profile-modal-body{padding:0 18px 22px}.om-profile-modal-avatar{width:108px;height:108px;margin-top:-54px;border-width:5px}.om-profile-modal-head{display:block}.om-profile-modal-actions{margin-top:14px}.om-profile-modal-actions button{flex:1}.om-profile-modal-stats{grid-template-columns:1fr 1fr}.om-profile-modal-stat:last-child{grid-column:1/-1}}
  `;document.head.appendChild(s)}
  async function open(id){
    styles();close();
    const backdrop=document.createElement('div');backdrop.className='om-profile-modal-backdrop';backdrop.innerHTML='<div class="om-profile-modal"><div class="om-profile-modal-loading">Loading profile…</div></div>';document.body.appendChild(backdrop);
    const modal=backdrop.firstElementChild;const closeBtn=()=>close();backdrop.addEventListener('click',e=>{if(e.target===backdrop)close()});document.addEventListener('keydown',escClose,{once:true});function escClose(e){if(e.key==='Escape')close()}
    try{
      const {data:p,error}=await db.from('profiles').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!p)throw new Error('Profile not found.');
      const me=(await db.auth.getUser()).data.user?.id;let following=false,followers=0,followingCount=0;
      if(me){const [f,a,b]=await Promise.all([db.from('profile_follows').select('follower_id').eq('follower_id',me).eq('following_id',id).maybeSingle(),db.from('profile_follows').select('follower_id',{count:'exact',head:true}).eq('following_id',id),db.from('profile_follows').select('following_id',{count:'exact',head:true}).eq('follower_id',id)]);following=!!f.data;followers=a.count||0;followingCount=b.count||0}
      const posts=await db.from('posts').select('*').eq('author_id',id).order('created_at',{ascending:false}).limit(5);
      const postRows=(posts.data||[]).map(x=>`<div class="om-profile-modal-post">${esc(x.body||x.content||x.text||'')}</div>`).join('');
      const bg=backgrounds[bgName(p)]||backgrounds.default;const x=xp(p);const loc=[p.city,p.state,p.country].filter(Boolean).join(', ');const rank=p.rank||p.rank_name||p.profile_title||'Member';
      modal.style.setProperty('--om-accent',accent(p));modal.style.setProperty('--om-bg',bg);
      modal.innerHTML=`<div class="om-profile-modal-banner"><span class="om-profile-modal-label">People · Public Profile</span><button class="om-profile-modal-close" aria-label="Close">×</button></div><div class="om-profile-modal-body"><div class="om-profile-modal-avatar"><img src="${esc(avatar(p))}" alt="${esc(name(p))} avatar"></div><div class="om-profile-modal-head"><div><h2>${esc(name(p))}</h2><div class="om-profile-modal-handle">@${esc(p.username||'member')} · ${esc(rank)}</div><p class="om-profile-modal-bio">${esc(p.bio||'Member of the OneMuslim community.')}</p></div>${me&&me!==id?`<div class="om-profile-modal-actions"><button class="follow" id="omProfileFollow">${following?'Following':'Follow'}</button><button id="omProfileMessage">Message</button></div>`:''}</div><div class="om-profile-modal-chips">${loc?`<span class="om-profile-modal-chip">📍 ${esc(loc)}</span>`:''}<span class="om-profile-modal-chip">⭐ ${x.toLocaleString()} XP</span>${x>=10000?'<span class="om-profile-modal-chip">✦ Platinum</span>':''}</div><div class="om-profile-modal-stats"><div class="om-profile-modal-stat"><b id="omProfileFollowers">${followers}</b><span>Followers</span></div><div class="om-profile-modal-stat"><b>${followingCount}</b><span>Following</span></div><div class="om-profile-modal-stat"><b>${esc(rank)}</b><span>Rank</span></div></div><div class="om-profile-modal-theme"><strong>Profile design</strong><br>${esc(bgName(p))} background · ${esc(p.profile_accent||'emerald')} accent${x>=10000?' · Platinum avatar':''}</div><section class="om-profile-modal-posts"><h3>Posts</h3>${postRows||'<div class="om-profile-modal-empty">No posts yet.</div>'}</section></div>`;
      modal.querySelector('.om-profile-modal-close').onclick=closeBtn;
      modal.querySelector('#omProfileMessage')?.addEventListener('click',()=>window.openDmWith?.(id));
      modal.querySelector('#omProfileFollow')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{if(following){const r=await db.from('profile_follows').delete().eq('follower_id',me).eq('following_id',id);if(r.error)throw r.error;following=false}else{const r=await db.from('profile_follows').insert({follower_id:me,following_id:id});if(r.error)throw r.error;following=true}b.textContent=following?'Following':'Follow';const c=await db.from('profile_follows').select('follower_id',{count:'exact',head:true}).eq('following_id',id);modal.querySelector('#omProfileFollowers').textContent=c.count||0;window.dispatchEvent(new CustomEvent('profile:follow-changed',{detail:{profileId:id,following}}))}catch(err){window.toast?.(err.message||'Unable to update follow.')}finally{b.disabled=false}});
    }catch(err){modal.innerHTML=`<button class="om-profile-modal-close" style="position:absolute;right:15px;top:15px" aria-label="Close">×</button><div class="om-profile-modal-loading">Unable to load this profile.<br><small>${esc(err.message||'Please try again.')}</small></div>`;modal.querySelector('button').onclick=closeBtn}
  }
  function close(){document.querySelector('.om-profile-modal-backdrop')?.remove()}
  window.OneMuslimOpenProfileModal=open;window.OneMuslimCloseProfileModal=close;
})();