/* OneMuslim Profile Follows — follow/unfollow, follower/following counts, and profile lists. */
(function(){
'use strict';
const client=()=>window.OneMuslimSupabaseClient?.getClient?.()||window.supabase?.createClient?.(window.APP_CONFIG?.SUPABASE_URL,window.APP_CONFIG?.SUPABASE_ANON_KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let currentUser=null;
async function getUser(){const sb=client();if(!sb)return null;const r=await sb.auth.getUser();currentUser=r?.data?.user||null;return currentUser;}
async function counts(sb,id){const [a,b]=await Promise.all([
 sb.from('profile_follows').select('*',{count:'exact',head:true}).eq('following_id',id),
 sb.from('profile_follows').select('*',{count:'exact',head:true}).eq('follower_id',id)
]);return {followers:a.count||0,following:b.count||0};}
async function isFollowing(sb,me,id){if(!me||me===id)return false;const r=await sb.from('profile_follows').select('follower_id').eq('follower_id',me).eq('following_id',id).maybeSingle();return !!r.data;}
function targetIdFrom(root){return root?.dataset?.profileId||root?.querySelector?.('[data-profile-id]')?.dataset?.profileId||root?.dataset?.userId||null;}
async function render(root,id){const sb=client();if(!sb||!id)return;const me=(await getUser())?.id||null;const [c,following]=await Promise.all([counts(sb,id),isFollowing(sb,me,id)]);let box=root.querySelector('.om-follow-box');if(!box){box=document.createElement('div');box.className='om-follow-box';root.appendChild(box)}box.innerHTML=`<div class="om-follow-stats"><button type="button" data-follow-list="followers"><b>${c.followers}</b><span>Followers</span></button><button type="button" data-follow-list="following"><b>${c.following}</b><span>Following</span></button></div>${me&&me!==id?`<button type="button" class="om-follow-btn ${following?'is-following':''}" data-follow-target="${esc(id)}">${following?'Following':'Follow'}</button>`:''}`;}
async function toggle(btn){const sb=client();const me=(await getUser())?.id;const id=btn.dataset.followTarget;if(!sb||!me||!id||me===id)return;btn.disabled=true;try{const existing=await sb.from('profile_follows').select('follower_id').eq('follower_id',me).eq('following_id',id).maybeSingle();if(existing.data)await sb.from('profile_follows').delete().eq('follower_id',me).eq('following_id',id);else await sb.from('profile_follows').insert({follower_id:me,following_id:id});const root=btn.closest('[data-profile-id]')||btn.closest('#profilePanel')||btn.parentElement;await render(root,id);window.dispatchEvent(new CustomEvent('profile:follow-changed',{detail:{profileId:id,following:!existing.data}}));}catch(e){console.error('[OneMuslim] follow failed',e);window.toast?.(e?.message||'Unable to update follow.')}finally{btn.disabled=false}}
async function openList(root,id,type){const sb=client();if(!sb)return;const column=type==='followers'?'following_id':'follower_id';const relation=type==='followers'?'follower_id':'following_id';const r=await sb.from('profile_follows').select(`${relation}, profiles:${relation}(id,username,display_name,avatar_config,avatar_gender)`).eq(column,id);if(r.error){console.error(r.error);return}const rows=(r.data||[]).map(x=>x.profiles).filter(Boolean);const modal=document.createElement('div');modal.className='om-follow-modal';modal.innerHTML=`<div class="om-follow-modal-card"><button class="om-follow-close" type="button">×</button><h3>${type==='followers'?'Followers':'Following'}</h3><div class="om-follow-list">${rows.length?rows.map(p=>`<button type="button" class="om-follow-person" data-profile-id="${esc(p.id)}"><span class="om-follow-avatar">${esc((p.display_name||p.username||'?').charAt(0).toUpperCase())}</span><span><b>${esc(p.display_name||p.username||'Member')}</b><small>@${esc(p.username||'member')}</small></span></button>`).join(''):'<div class="om-follow-empty">No one here yet.</div>'}</div></div>`;document.body.appendChild(modal);modal.querySelector('.om-follow-close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove();});modal.querySelectorAll('.om-follow-person').forEach(b=>b.onclick=()=>{modal.remove();window.OneMuslimProfileFollows?.showProfile?.(b.dataset.profileId)});}
function styles(){if(document.getElementById('om-follow-css'))return;const s=document.createElement('style');s.id='om-follow-css';s.textContent=`.om-follow-box{display:flex;align-items:center;gap:18px;margin:14px 0}.om-follow-stats{display:flex;gap:18px}.om-follow-stats button{border:0;background:none;display:grid;gap:2px;cursor:pointer;color:#20352c}.om-follow-stats b{font-size:18px}.om-follow-stats span{font-size:12px;opacity:.7}.om-follow-btn{border:0;border-radius:10px;padding:9px 18px;background:#1f6a55;color:#fff;font-weight:700;cursor:pointer}.om-follow-btn.is-following{background:#eef4ef;color:#1f6a55;border:1px solid #cbded4}.om-follow-modal{position:fixed;inset:0;background:rgba(7,28,22,.42);display:grid;place-items:center;z-index:9999;padding:20px}.om-follow-modal-card{width:min(420px,100%);max-height:75vh;overflow:auto;background:#fffdf8;border-radius:20px;padding:22px;position:relative}.om-follow-close{position:absolute;right:14px;top:10px;border:0;background:none;font-size:28px;cursor:pointer}.om-follow-list{display:grid;gap:8px;margin-top:15px}.om-follow-person{display:flex;align-items:center;gap:11px;padding:10px;border:0;border-radius:12px;background:#f3f7f4;text-align:left;cursor:pointer}.om-follow-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#1f6a55;color:#fff;font-weight:700}.om-follow-person span:nth-child(2){display:grid;gap:2px}.om-follow-person small{opacity:.65}.om-follow-empty{padding:20px;text-align:center;opacity:.65}`;document.head.appendChild(s)}
function init(){styles();document.addEventListener('click',e=>{const f=e.target.closest?.('[data-follow-target]');if(f){toggle(f);return}const l=e.target.closest?.('[data-follow-list]');if(l){const root=l.closest('[data-profile-id]')||l.closest('#profilePanel');const id=targetIdFrom(root);if(id)openList(root,id,l.dataset.followList)}});}
function mountProfile(id){const panel=document.getElementById('profilePanel');if(!panel)return;panel.dataset.profileId=id;render(panel,id)}
async function showProfile(id){const sb=client();if(!sb||!id)return;const r=await sb.from('profiles').select('*').eq('id',id).maybeSingle();if(!r.data)return;window.profile=r.data;mountProfile(id);window.OneMuslimProfileFollows.lastProfile=r.data;}
window.OneMuslimProfileFollows={render,mountProfile,showProfile,counts};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
