/* OneMuslim Profile Builder — premium mobile-first editor */
(function(){
  'use strict';
  const AVATARS={male:'assets/avatar/male/male-1-original.jpg',female:'assets/avatar/female/female-base.png'};
  const themes=[
    {id:'mosque',name:'Mosque Silhouette',css:'linear-gradient(135deg,#fbf1dc 0%,#ead5ad 100%)',icon:'☪'},
    {id:'gold',name:'Luxury Gold',css:'linear-gradient(135deg,#fff8e8 0%,#ead7ad 100%)',icon:'✦'},
    {id:'geometry',name:'Islamic Geometry',css:'linear-gradient(135deg,#fbf7ed 0%,#efe3cc 100%)',icon:'◇'}
  ];
  const accents=[['emerald','#1f6a55'],['gold','#c89d3c'],['navy','#243b62'],['plum','#70536f']];
  const packages=[['default','Starter','Free'],['gold_package','Scholar','Expert+'],['elite_package','Elite','Elite Sheikh+'],['platinum_package','Muhsin','Platinum']];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const getSaved=()=>{try{return JSON.parse(localStorage.getItem('onemuslim_profile_customization')||'{}')}catch{return{}}};
  const getPageProfile=()=>{const saved=getSaved();const panel=document.getElementById('profilePanel');const name=(panel?.querySelector('.profile-hero h2')?.textContent||document.querySelector('.mini-profile b')?.textContent||'Your Name').trim();const user=(document.querySelector('.mini-profile small')?.textContent||'').split('·')[0].trim().replace(/^@/,'');const xp=document.getElementById('sidebarXp')?.textContent||'0';return Object.assign({avatar_gender:'male',avatar_package:'default',profile_background:'mosque',profile_accent:'emerald',avatar_ring:'default',profile_title:'Muslim',bio:'',profile_visibility:'public',group_team:''},saved,{display_name:name,username:user,xp:Number(String(xp).replace(/[^0-9]/g,''))||0});};
  function avatarHtml(gender,cls=''){const src=AVATARS[gender]||AVATARS.male;return `<img class="om-pb-avatar-img ${cls}" src="${src}" alt="" onerror="this.style.display='none';this.parentElement.classList.add('om-pb-avatar-fallback')">`;}
  function open(){
    const p=getPageProfile();
    const o=document.createElement('div');o.className='om-pb-overlay';o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');
    o.innerHTML=`<section class="om-pb-shell">
      <header class="om-pb-top"><button class="om-pb-back" aria-label="Back">←</button><div><span class="om-pb-kicker">ONE MUSLIM · PROFILE</span><h2>Edit Profile</h2></div><button class="om-pb-close" aria-label="Close">×</button></header>
      <div class="om-pb-preview-wrap"><div class="om-pb-preview" id="pbPreviewCard"><div class="om-pb-preview-banner" id="pbPreviewBanner"></div><div class="om-pb-preview-body"><div class="om-pb-preview-avatar" id="pbPreviewAvatar">${avatarHtml(p.avatar_gender)}</div><button class="om-pb-pencil" aria-label="Change avatar">✎</button><div class="om-pb-preview-name" id="pbName">${esc(p.display_name)}</div><div class="om-pb-preview-meta">@${esc(p.username||'username')}</div><div class="om-pb-preview-stats"><span><b id="pbXp">${p.xp.toLocaleString()}</b> XP</span><span><b>Active</b> status</span><span><b>${esc(p.profile_title)}</b> rank</span></div></div></div></div>
      <nav class="om-pb-tabs" aria-label="Profile editor"><button class="om-pb-tab active" data-tab="avatar"><span>◉</span>Avatar</button><button class="om-pb-tab" data-tab="background"><span>▧</span>Background</button><button class="om-pb-tab" data-tab="style"><span>✦</span>Style</button><button class="om-pb-tab" data-tab="profile"><span>◎</span>Profile</button><button class="om-pb-tab" data-tab="privacy"><span>⌁</span>Privacy</button></nav>
      <main class="om-pb-main">
        <section class="om-pb-panel active" data-panel="avatar"><div class="om-pb-heading"><span class="om-pb-kicker">IDENTITY</span><h3>Choose your avatar</h3><p>Keep it simple, recognizable, and unmistakably One Muslim.</p></div><div class="om-pb-card"><label>Base avatar</label><div class="om-pb-avatar-grid"><button class="om-pb-avatar-choice ${p.avatar_gender!=='female'?'selected':''}" data-gender="male">${avatarHtml('male')}<strong>Male</strong><small>Islamic silhouette</small></button><button class="om-pb-avatar-choice ${p.avatar_gender==='female'?'selected':''}" data-gender="female">${avatarHtml('female')}<strong>Female</strong><small>Hijab silhouette</small></button></div></div><div class="om-pb-card"><label>Avatar package</label><div class="om-pb-package-grid">${packages.map(x=>`<button class="om-pb-package ${p.avatar_package===x[0]?'selected':''} ${x[0]!=='default'?'locked':''}" data-package="${x[0]}" ${x[0]!=='default'?'disabled':''}><span>${x[0]==='default'?'✦':x[0]==='gold_package'?'◇':x[0]==='elite_package'?'✥':'✧'}</span><strong>${x[1]}</strong><small>${x[2]}</small>${x[0]!=='default'?'<i>🔒</i>':''}</button>`).join('')}</div><p class="om-pb-note">Packages unlock permanently as your rank grows.</p></div></section>
        <section class="om-pb-panel" data-panel="background"><div class="om-pb-heading"><span class="om-pb-kicker">ATMOSPHERE</span><h3>Choose your theme</h3><p>Your profile background can also become the visual language of your posts.</p></div><div class="om-pb-theme-grid">${themes.map(t=>`<button class="om-pb-theme ${p.profile_background===t.id?'selected':''}" data-bg="${t.id}"><span class="om-pb-theme-art" style="background:${t.css}"><b>${t.icon}</b></span><strong>${t.name}</strong><small>${t.id==='mosque'?'Warm mosque silhouette':t.id==='gold'?'Cream, gold & ornament':'Subtle repeating geometry'}</small></button>`).join('')}</div></section>
        <section class="om-pb-panel" data-panel="style"><div class="om-pb-heading"><span class="om-pb-kicker">PERSONAL STYLE</span><h3>Make it yours</h3><p>These details travel with your identity across One Muslim.</p></div><div class="om-pb-card"><label>Accent color</label><div class="om-pb-swatches">${accents.map(a=>`<button class="om-pb-swatch ${p.profile_accent===a[0]?'selected':''}" data-accent="${a[0]}" style="background:${a[1]}" aria-label="${a[0]}"></button>`).join('')}</div></div><div class="om-pb-card"><label>Avatar ring</label><div class="om-pb-ring-grid"><button class="om-pb-ring ${p.avatar_ring==='default'?'selected':''}" data-ring="default">Classic</button><button class="om-pb-ring gold ${p.avatar_ring==='gold'?'selected':''}" data-ring="gold">Gold</button><button class="om-pb-ring emerald ${p.avatar_ring==='emerald'?'selected':''}" data-ring="emerald">Emerald</button></div></div><div class="om-pb-lock"><span>🔒</span><div><strong>Custom photo</strong><small>Unlock at Platinum Muhsin. Upload or take your own photo.</small></div></div></section>
        <section class="om-pb-panel" data-panel="profile"><div class="om-pb-heading"><span class="om-pb-kicker">PROFILE DETAILS</span><h3>Tell the community</h3><p>Keep your profile useful without making it feel like a form.</p></div><div class="om-pb-card"><label>Bio</label><textarea id="pbBio" maxlength="280" placeholder="Tell the community about yourself">${esc(p.bio||'')}</textarea></div><div class="om-pb-card"><label>Group or team</label><input id="pbGroup" maxlength="80" value="${esc(p.group_team||'')}" placeholder="Your group or team"></div></section>
        <section class="om-pb-panel" data-panel="privacy"><div class="om-pb-heading"><span class="om-pb-kicker">CONTROL</span><h3>Privacy & visibility</h3><p>Private profiles won't appear in People or group/team discovery.</p></div><div class="om-pb-privacy-row"><div><strong>Profile visibility</strong><small>Choose who can discover you.</small></div><select id="pbPrivacy"><option value="public" ${p.profile_visibility!=='private'?'selected':''}>Public</option><option value="private" ${p.profile_visibility==='private'?'selected':''}>Private</option></select></div></section>
        <footer class="om-pb-actions"><button class="om-pb-btn" id="pbCancel">Cancel</button><button class="om-pb-btn primary" id="pbSave">Save changes</button></footer>
      </main>
    </section>`;
    document.body.appendChild(o);
    let draft={...p};
    const preview=()=>{const theme=themes.find(t=>t.id===draft.profile_background)||themes[0];o.querySelector('#pbPreviewBanner').style.background=theme.css;o.querySelector('#pbPreviewAvatar').innerHTML=avatarHtml(draft.avatar_gender);o.querySelector('#pbName').textContent=draft.display_name;o.querySelector('#pbXp').textContent=Number(draft.xp||0).toLocaleString();const col=accents.find(a=>a[0]===draft.profile_accent)?.[1]||'#1f6a55';o.querySelector('#pbPreviewCard').style.setProperty('--pb-accent',col);};
    const close=()=>o.remove();
    o.querySelector('.om-pb-close').onclick=close;o.querySelector('.om-pb-back').onclick=close;o.querySelector('#pbCancel').onclick=close;o.addEventListener('click',e=>{if(e.target===o)close()});
    o.querySelectorAll('.om-pb-tab').forEach(t=>t.onclick=()=>{o.querySelectorAll('.om-pb-tab').forEach(x=>x.classList.toggle('active',x===t));o.querySelectorAll('.om-pb-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===t.dataset.tab));o.querySelector('.om-pb-main').scrollTop=0;});
    o.querySelectorAll('.om-pb-avatar-choice').forEach(b=>b.onclick=()=>{draft.avatar_gender=b.dataset.gender;o.querySelectorAll('.om-pb-avatar-choice').forEach(x=>x.classList.toggle('selected',x===b));preview();});
    o.querySelectorAll('.om-pb-theme').forEach(b=>b.onclick=()=>{draft.profile_background=b.dataset.bg;o.querySelectorAll('.om-pb-theme').forEach(x=>x.classList.toggle('selected',x===b));preview();});
    o.querySelectorAll('.om-pb-swatch[data-accent]').forEach(b=>b.onclick=()=>{draft.profile_accent=b.dataset.accent;o.querySelectorAll('[data-accent]').forEach(x=>x.classList.toggle('selected',x===b));preview();});
    o.querySelectorAll('.om-pb-ring').forEach(b=>b.onclick=()=>{draft.avatar_ring=b.dataset.ring;o.querySelectorAll('.om-pb-ring').forEach(x=>x.classList.toggle('selected',x===b));preview();});
    o.querySelector('#pbSave').onclick=async()=>{draft.bio=o.querySelector('#pbBio').value.trim();draft.group_team=o.querySelector('#pbGroup').value.trim();draft.profile_visibility=o.querySelector('#pbPrivacy').value;localStorage.setItem('onemuslim_profile_customization',JSON.stringify(draft));try{if(window.APP_CONFIG?.SUPABASE_URL&&window.supabase){const client=window.supabase.createClient(window.APP_CONFIG.SUPABASE_URL,window.APP_CONFIG.SUPABASE_ANON_KEY);await client.from('profiles').update({gender:draft.avatar_gender,bio:draft.bio}).eq('id',draft.id)}}catch(e){}close();window.OneMuslimProfileUI?.apply?.(draft);};
    preview();
  }
  function wire(){const b=document.getElementById('editProfile');if(b&&!b.dataset.pbv3){b.dataset.pbv3='1';b.onclick=open;}}
  function init(){wire();new MutationObserver(wire).observe(document.body,{childList:true,subtree:true});}
  window.OneMuslimProfileUI={apply:p=>{document.body.dataset.profileBackground=p.profile_background||'mosque';document.body.dataset.profileAccent=p.profile_accent||'emerald';}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
