/* OneMuslim Profile Landing — single personal card + OneReport. */
(function(){
'use strict';
let syncing=false;
let rendering=false;
function client(){return window.OneMuslimSupabaseClient?.getClient?.()||window.supabase?.createClient?.(window.APP_CONFIG?.SUPABASE_URL,window.APP_CONFIG?.SUPABASE_ANON_KEY)}
async function syncProfile(){if(syncing)return window.profile||null;const sb=client();if(!sb)return null;syncing=true;try{const {data:{user}}=await sb.auth.getUser();if(!user)return null;const {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;if(data)window.profile=data;return data||null}catch(e){console.error('Profile sync failed:',e);return window.profile||null}finally{syncing=false}}
function openEditor(){const open=window.OneMuslimProfileBuilder?.open||window.openProfileBuilder||window.OneMuslimOpenProfileEditor;if(typeof open!=='function'){window.toast?.('Profile editor is still loading. Please try again.');return false}return open()}
function styles(){if(document.getElementById('om-profile-card-styles'))return;const s=document.createElement('style');s.id='om-profile-card-styles';s.textContent=`
.om-personal-card{position:relative;overflow:hidden;margin:0 0 30px;border:1px solid #e5dfd0;border-radius:28px;min-height:1500px;background:#fff;box-shadow:0 18px 55px rgba(18,48,39,.10)}
.om-personal-card-bg{position:absolute;inset:0;height:390px;background-size:cover;background-position:center top}
.om-personal-card-bg:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(5,34,27,.02) 0%,rgba(255,255,255,.03) 55%,rgba(255,255,255,.22) 100%)}
.om-personal-card-fg{position:relative;z-index:1;margin-top:330px;min-height:1170px;background:rgba(255,255,255,.98);border-radius:34px 34px 28px 28px;padding:78px 26px 34px}
.om-personal-avatar{position:absolute;left:50%;top:0;transform:translate(-50%,-58%);width:88px;height:88px;aspect-ratio:1/1;border-radius:50%;border:5px solid #fff;box-sizing:border-box;box-shadow:0 10px 28px rgba(18,48,39,.20),0 0 0 1px rgba(200,157,60,.14);background:#dce7e0;overflow:hidden;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:26px;color:#173c31;flex:none;z-index:3}
.om-personal-avatar img{width:100%;height:100%;object-fit:contain;display:block}
.om-personal-card-head{display:flex;align-items:flex-start;gap:16px}.om-personal-name{font-size:27px;font-weight:800;color:#18362c}.om-personal-user{font-size:14px;color:#708078;margin-top:4px}.om-personal-rank{margin-left:auto;text-align:right}.om-personal-rank strong{display:block;color:#c89d3c;font-size:18px}.om-personal-rank span{font-size:12px;color:#61756b}
.om-personal-progress{height:9px;border-radius:99px;background:#e5ece8;overflow:hidden;margin:24px 0 8px}.om-personal-progress i{display:block;height:100%;background:linear-gradient(90deg,#1f6a55,#c89d3c);border-radius:99px}.om-personal-xp{text-align:right;font-size:11px;color:#63766d}.om-personal-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;border-top:1px solid #eee9df;margin-top:20px;padding-top:18px}.om-personal-stat{text-align:center}.om-personal-stat b{display:block;color:#1d4e40;font-size:21px}.om-personal-stat span{font-size:11px;color:#728078}.om-personal-actions{display:flex;gap:10px;margin-top:22px}.om-personal-action{flex:1;border:1px solid #cbded4;background:#fff;color:#1f5b49;border-radius:14px;padding:12px;font-weight:800}.om-personal-action.primary{background:#1f5b49;color:#fff;border-color:#1f5b49}.om-report-panel{margin-top:14px}
.om-pb-avatar-photo,.om-pb-preview-avatar{aspect-ratio:1/1!important;border-radius:50%!important;overflow:hidden!important;box-sizing:border-box!important;flex:0 0 auto!important}.om-pb-avatar-photo{width:88px!important;height:88px!important;min-width:88px!important;min-height:88px!important}.om-pb-avatar-photo img,.om-pb-preview-avatar img{width:100%!important;height:100%!important;object-fit:contain!important;display:block!important}
@media(max-width:620px){.om-personal-card{border-radius:22px;min-height:1500px}.om-personal-card-bg{height:360px}.om-personal-card-fg{margin-top:305px;min-height:1195px;padding:70px 18px 28px}.om-personal-avatar{width:84px;height:84px;transform:translate(-50%,-58%)}.om-personal-name{font-size:23px}.om-personal-actions{flex-direction:column}}
`;document.head.appendChild(s)}
function avatarFor(p){const system=window.OneMuslimProfileSystem;const derived=system?.getAvatarAsset?.(p);if(derived)return derived;const cfg=p?.avatar_config;const candidates=[cfg?.asset,cfg?.url,cfg?.avatar_url,cfg?.image,cfg?.path,cfg?.selectedAvatar,cfg?.selected_avatar,p?.avatar_url].filter(v=>typeof v==='string'&&v.trim());return candidates[0]||''}
function backgroundFor(p){const name=p?.profile_background||p?.background||p?.background_theme||'default';const b={'Islamic Geometry':'linear-gradient(135deg,#fbf5e8,#f1e6cf)','Mosque Silhouette':'linear-gradient(135deg,#f1dfbb,#d2b77a)','Islamic Arch':'linear-gradient(135deg,#eee2c9,#c9b58d)','Crescent & Stars':'linear-gradient(135deg,#0b2630,#173f52)','Luxury Gold':'linear-gradient(135deg,#fff5d9,#c89d3c)','Emerald':'linear-gradient(135deg,#0d4b3d,#1f6b57)','Dark Mosque':'linear-gradient(135deg,#061e1a,#173a31)','Minimal Cream':'linear-gradient(135deg,#fffdf8,#eee8dc)','default':'linear-gradient(135deg,#0e4437,#214e42)'};return b[name]||b.default}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const panel=document.getElementById('profilePanel');if(!panel||rendering)return;styles();rendering=true;try{const oldReport=document.getElementById('oneReportPanel');if(oldReport)oldReport.remove();const p=window.profile||{};const xp=Number(p.xp_total??p.xp??0)||0;const rank=p.profile_title||window.OneMuslimProfileSystem?.getTier?.(p)?.label||'Muslim';const title=rank==='Muslim'?'Seeker of Truth':rank;const tier=window.OneMuslimProfileSystem?.getTierProgress?.(p);const next=tier?.nextTier;const percent=tier?.percent??Math.min(100,(xp%5000)/50);const avatar=avatarFor(p);const name=p.display_name||`${p.first_name||''} ${p.last_name||''}`.trim()||'Your Name';const following=Number(p.following_count??p.following??0)||0;const badges=Number(p.badges_count??p.badges??0)||0;
panel.innerHTML='';
const card=document.createElement('article');card.className='om-personal-card';card.innerHTML=`<div class="om-personal-card-bg" style="background:${backgroundFor(p)}"></div><div class="om-personal-card-fg"><div class="om-personal-avatar">${avatar?`<img src="${escapeHtml(avatar)}" alt="Selected avatar">`:escapeHtml((name.match(/\b\w/g)||[]).slice(0,2).join('')).toUpperCase()}</div><div class="om-personal-card-head"><div><div class="om-personal-name">${escapeHtml(name)}</div><div class="om-personal-user">@${escapeHtml(p.username||'username')}</div></div><div class="om-personal-rank"><strong>${escapeHtml(title)}</strong><span>Rank ${window.OneMuslimProfileSystem?.rankIndex?.(rank)+1||1}</span></div></div><div class="om-personal-progress"><i style="width:${percent}%"></i></div><div class="om-personal-xp">${xp.toLocaleString()} XP${next?` · ${Math.max(0,next.minXP-xp).toLocaleString()} to ${escapeHtml(next.label)}`:''}</div><div class="om-personal-stats"><div class="om-personal-stat"><b>${xp.toLocaleString()}</b><span>Total XP</span></div><div class="om-personal-stat"><b>${badges}</b><span>Badges</span></div><div class="om-personal-stat"><b>${following}</b><span>Following</span></div></div><div class="om-personal-actions"><button class="om-personal-action primary" id="openProfileEditor">Edit profile</button><button class="om-personal-action" id="openOneReport">📊 OneReport</button></div></div>`;panel.appendChild(card);
card.querySelector('#openProfileEditor').onclick=()=>openEditor();card.querySelector('#openOneReport').onclick=async()=>{let host=document.getElementById('oneReportPanel');if(!host){host=document.createElement('div');host.id='oneReportPanel';host.className='om-report-panel';card.insertAdjacentElement('afterend',host)}host.classList.toggle('hidden');if(!host.classList.contains('hidden'))await window.OneMuslimOneReport?.render()}}finally{rendering=false}}
function observePanel(){const panel=document.getElementById('profilePanel');if(!panel||panel.dataset.omProfileObserver)return;panel.dataset.omProfileObserver='1';const observer=new MutationObserver(()=>{if(rendering)return;const first=panel.firstElementChild;if(!first||!first.classList.contains('om-personal-card'))render()});observer.observe(panel,{childList:true})}
function init(){observePanel();syncProfile().then(()=>{render()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.OneMuslimProfileLanding={render,syncProfile};
})();
