/* OneMuslim home release notes + persistent build indicator. */
(function(){
'use strict';
const VERSION='2026.09.02.03';
const CHANGES=[
'Coming Soon added to the main navigation and opens coming-soon.html',
'People cards: View Profile, Message, Follow',
'Profile card: Follow button in the top-right',
'Post emoji reactions: 😂 😭 😅 😁 🥰 😳 😏 🥺',
'Comment emoji reactions with independent counts',
'DM: New message / start a conversation',
'Follow + Following state saved to Supabase'
];
function styles(){if(document.getElementById('om-release-notes-css'))return;const s=document.createElement('style');s.id='om-release-notes-css';s.textContent=`.om-release-notes{width:min(270px,100%);margin-top:14px;background:rgba(255,255,255,.92);border:1px solid #d8e7dc;border-radius:15px;box-shadow:0 8px 24px rgba(24,49,36,.08);overflow:hidden;color:#183124;text-align:left}.om-release-toggle{width:100%;border:0;background:transparent;padding:11px 13px;display:flex;align-items:center;justify-content:space-between;gap:10px;color:#183124;font-weight:900;font-size:11px;cursor:pointer}.om-release-toggle span:last-child{font-size:13px;transition:transform .2s}.om-release-notes.open .om-release-toggle span:last-child{transform:rotate(180deg)}.om-release-body{display:none;padding:0 13px 13px}.om-release-notes.open .om-release-body{display:block}.om-release-version{font-size:9px;letter-spacing:1.2px;font-weight:900;color:#168746;margin-bottom:8px}.om-release-body ul{margin:0;padding-left:17px;display:grid;gap:6px}.om-release-body li{font-size:10px;line-height:1.35;color:#60756a}.om-release-hint{margin-top:9px;font-size:9px;color:#8a9a91}.om-version-bot{position:fixed;right:18px;top:50%;transform:translateY(-50%);z-index:99999;display:flex;align-items:center;gap:9px;padding:8px 12px 8px 8px;border:1px solid #d8e2dc;border-radius:999px;background:rgba(255,253,248,.96);box-shadow:0 8px 28px rgba(24,44,37,.14);font:700 11px/1.1 Arial,sans-serif;color:#1f5b49;backdrop-filter:blur(10px);user-select:none}.om-version-bot .om-version-icon{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:#1f5b49;color:#fff;font-size:16px}.om-version-bot small{display:block;font-size:9px;font-weight:600;color:#718078;margin-top:2px}@media(max-width:900px){.om-release-notes{width:min(320px,100%)}}@media(max-width:700px){.om-version-bot{right:10px;top:auto;bottom:18px;transform:none;padding:7px 10px 7px 7px}.om-version-bot .om-version-icon{width:28px;height:28px}}`;document.head.appendChild(s)}
function decorate(){const zone=document.querySelector('#homePage .welcome-avatar-zone');if(zone&&!zone.querySelector('.om-release-notes')){const card=document.createElement('section');card.className='om-release-notes';card.innerHTML=`<button type="button" class="om-release-toggle" aria-expanded="false"><span>✦ What's in this version?</span><span>⌄</span></button><div class="om-release-body"><div class="om-release-version">BUILD ${VERSION}</div><ul>${CHANGES.map(x=>`<li>${x}</li>`).join('')}</ul><div class="om-release-hint">Use this checklist to verify the build you opened.</div></div>`;zone.appendChild(card);const b=card.querySelector('.om-release-toggle');b.onclick=()=>{const open=card.classList.toggle('open');b.setAttribute('aria-expanded',String(open))}}
if(!document.querySelector('.om-version-bot')){const bot=document.createElement('div');bot.className='om-version-bot';bot.setAttribute('aria-label','Website version updated');bot.innerHTML=`<span class="om-version-icon">🤖</span><span>Updated<small>v${VERSION}</small></span>`;document.body.appendChild(bot)}}
function init(){styles();decorate();const obs=new MutationObserver(decorate);obs.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
