(function(){
  const KEY='onemuslim_start_pack_v1';
  const state=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{xp:0,completed:[],bonusClaimed:false,path:'easy'}}catch(e){return {xp:0,completed:[],bonusClaimed:false,path:'easy'}}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const paths={easy:{label:'Easy Path',desc:'Short, beginner-friendly steps.'},fast:{label:'Fast Path',desc:'Move quickly through the essentials.'},deep:{label:'Deep Path',desc:'Spend more time on fundamentals.'}};
  const topics=[
    {id:'faith',title:'Faith & Tawhid',level:'Beginner → Fundamental',xp:500,desc:'Who Allah is, what worship means, and why Tawhid sits at the center of Islam.',body:'Start with the meaning of Tawhid, the three broad dimensions of worship, and the difference between knowing about Allah and worshipping Allah.'},
    {id:'quran',title:'Qur’an & Revelation',level:'Beginner → Fundamental',xp:500,desc:'How Muslims understand revelation, preservation, and the Qur’an’s role as guidance.',body:'Learn the basic categories of revelation, how the Qur’an is approached, and why Muslims treat it as the final revealed guidance.'},
    {id:'sunnah',title:'Sunnah & Hadith',level:'Beginner → Fundamental',xp:250,desc:'Understand Sunnah, Hadith, authenticity, and how prophetic guidance is used.',body:'Separate the concepts of Sunnah and Hadith, then learn why authentication and context matter when studying reports.'},
    {id:'seerah',title:'Seerah & Prophetic Model',level:'Beginner → Fundamental',xp:500,desc:'Meet the life, character, and mission of Prophet Muhammad ﷺ.',body:'Follow the broad arc of the Prophet’s mission and focus on character, patience, mercy, courage, and wisdom.'},
    {id:'history',title:'Islamic History',level:'Beginner → Fundamental',xp:250,desc:'Build a timeline that helps you place major people, movements, and events.',body:'Start with a simple timeline: revelation, the early Muslim community, expansion, scholarship, and later intellectual traditions.'},
    {id:'apologetics',title:'Apologetics & Worldview',level:'Fundamental → Deeper',xp:500,desc:'Learn to ask hard questions, define terms, and defend ideas without hostility.',body:'Practice steel-manning a question, identifying assumptions, distinguishing evidence from rhetoric, and answering with intellectual honesty.'},
    {id:'dawah',title:'Dawah & Dialogue',level:'Fundamental → Deeper',xp:250,desc:'Have serious conversations with adab, clarity, patience, and confidence.',body:'Learn a simple dialogue rhythm: listen, clarify, answer, acknowledge uncertainty, and keep good character when disagreement remains.'},
    {id:'influence',title:'Media & Influence',level:'Fundamental → Deeper',xp:100,desc:'Turn knowledge into responsible content, teaching, and community impact.',body:'Think about audience, evidence, storytelling, and responsibility before publishing Islamic educational content.'}
  ];
  const totalRead=topics.reduce((a,t)=>a+t.xp,0);
  function addXP(amount,id){const s=state();if(id&&s.completed.includes(id))return s;s.xp=Math.min(10000,s.xp+amount);if(id)s.completed.push(id);save(s);return s;}
  function pct(xp){return Math.min(100,Math.round((xp/10000)*100));}
  function render(root){
    if(!root)return; const s=state();
    root.innerHTML=`<section class="om-start-pack"><div class="sp-hero"><div><span class="sp-kicker">✦ START PACK · YOUR FIRST JOURNEY</span><h2>Know your faith. <em>Build your foundation.</em></h2><p>Choose how you want to learn, explore the essentials, and build momentum before you even create an account.</p></div><div class="sp-xp"><span>Journey XP</span><strong id="spXp">${s.xp.toLocaleString()}</strong><div class="sp-bar"><i id="spBar" style="width:${pct(s.xp)}%"></i></div><small>${s.xp>=10000?'Start Pack complete':'Every 1,000 XP marks your next milestone.'}</small></div></div><div class="sp-paths"><button data-path="easy" class="${s.path==='easy'?'active':''}"><b>Easy Path</b><small>Short + steady</small></button><button data-path="fast" class="${s.path==='fast'?'active':''}"><b>Fast Path</b><small>Move through essentials</small></button><button data-path="deep" class="${s.path==='deep'?'active':''}"><b>Deep Path</b><small>Fundamentals first</small></button></div><div class="sp-intro"><div><span class="sp-kicker">HOW IT WORKS</span><h3>Basics first. Fundamentals next. Depth when you're ready.</h3><p>Reading sections earns <b>100–500 XP</b>. Finish every Start Pack topic and the journey unlocks a <b>10,000 XP completion reward</b>.</p></div><div class="sp-locked">🔐 <b>10,000 XP</b><small>Create an account to redeem and store your completed Start Pack reward.</small></div></div><div class="sp-topics">${topics.map((t,i)=>`<article class="sp-topic ${s.completed.includes(t.id)?'done':''}"><div class="sp-number">0${i+1}</div><div class="sp-topic-body"><div class="sp-topic-meta"><span>${t.level}</span><b>+${t.xp} XP</b></div><h4>${t.title}</h4><p>${t.desc}</p><button data-topic="${t.id}">${s.completed.includes(t.id)?'Completed ✓':'Read section →'}</button></div></article>`).join('')}</div><div class="sp-footer"><div><span class="sp-kicker">THE FINISH LINE</span><h3>${s.completed.length===topics.length?'You completed the Start Pack. 🎉':'Complete all 8 topics to finish your Start Pack.'}</h3><p>${s.completed.length===topics.length?'Create an account to redeem and store your 10,000 XP reward.':'Your progress stays on this device until you create an account.'}</p></div><button id="spAccount" class="sp-primary">${s.completed.length===topics.length?'Create account & redeem 10,000 XP':'Create your OneMuslim account'}</button></div></section>`;
    root.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>{const n=state();n.path=b.dataset.path;save(n);render(root)});
    root.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{const t=topics.find(x=>x.id===b.dataset.topic);if(!t)return;const modal=document.createElement('div');modal.className='sp-modal';modal.innerHTML=`<div class="sp-modal-card"><button class="sp-close" aria-label="Close">×</button><span class="sp-kicker">${t.level} · +${t.xp} XP</span><h3>${t.title}</h3><p>${t.body}</p><div class="sp-reading"><b>Read this idea twice.</b><span>Then mark the section complete to earn your XP.</span></div><button class="sp-primary" id="spComplete">Mark section complete · +${t.xp} XP</button></div>`;document.body.appendChild(modal);modal.querySelector('.sp-close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});modal.querySelector('#spComplete').onclick=()=>{addXP(t.xp,t.id);modal.remove();render(root)}});
    root.querySelector('#spAccount').onclick=()=>window.OneMuslimStartPack.openSignup();
  }
  window.OneMuslimStartPack={topics,paths,totalRead,render,getState:state,reset:()=>localStorage.removeItem(KEY),openSignup:()=>document.getElementById('openSignup')?.click(),async redeemGuestXp(sb,userId){const s=state();if(!s.xp||s.completed.length<topics.length||s.bonusClaimed)return 0;const {data,error}=await sb.from('profiles').select('xp_total').eq('id',userId).maybeSingle();if(error||!data)return 0;const next=Number(data.xp_total||0)+10000;const upd=await sb.from('profiles').update({xp_total:next}).eq('id',userId);if(upd.error)return 0;s.bonusClaimed=true;save(s);return 10000;}};
})();